#!/usr/bin/env bash
#
# Publish emulator evidence (screenshots + log dumps) to an orphan branch so each
# run has a stable raw.githubusercontent.com URL to link from the job summary.
#
# Deliberately non-fatal: CI must never go red because a documentation-only push
# failed. Any caller should keep `continue-on-error: true` anyway.
set -u -o pipefail

SRC="${1:-android-rs/screenshots}"
BRANCH="${2:-debug/android-emulator-latest}"

[ -n "${GITHUB_TOKEN:-}" ] || { echo "GITHUB_TOKEN unset - skipping screenshot publish"; exit 0; }
[ -d "$SRC" ] || { echo "no evidence dir ($SRC) - skipping"; exit 0; }

mapfile -t FILES < <(find "$SRC" -maxdepth 1 -type f \( -name '*.png' -o -name '*.txt' -o -name '*.xml' \) | sort)
if [ "${#FILES[@]}" -eq 0 ]; then
  echo "no files in $SRC - skipping"
  exit 0
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git -C "$WORK" init -q
git -C "$WORK" config user.name "github-actions[bot]"
git -C "$WORK" config user.email "41898282+github-actions[bot]@users.noreply.github.com"

for f in "${FILES[@]}"; do cp "$f" "$WORK/"; done
sha="${GITHUB_SHA:-unknown}"
{
  printf '# Emulator evidence\n\n'
  printf 'Generated by the "Android Emulator Smoke Test" workflow for commit `%s`.\n\n' "$sha"
  printf 'Run: %s\n\n' "${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-}/actions/runs/${GITHUB_RUN_ID:-}"
  printf '| file | bytes |\n|---|---|\n'
  for f in "${FILES[@]}"; do printf '| [%s](./%s) | %s |\n' "$(basename "$f")" "$(basename "$f")" "$(wc -c < "$f")"; done
} > "$WORK/README.md"

git -C "$WORK" add -A
git -C "$WORK" commit -q -m "chore: emulator evidence for ${sha:0:7} [skip ci]"

URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
# Redact the token: git echoes the remote URL back on auth failures.
if git -C "$WORK" push --force "$URL" "HEAD:refs/heads/$BRANCH" 2>&1 |
   sed -E 's#https://[^@]*@#https://***@#g' | sed 's/^/  /'; then
  echo "pushed $((${#FILES[@]} + 1)) files to $BRANCH"
else
  echo "::warning::could not push $BRANCH"
  exit 0
fi

BASE="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${BRANCH}"
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  {
    printf '\n### Emulator screenshots\n\n'
    for f in "${FILES[@]}"; do
      case "$f" in
        *.png) printf '![](%s/%s)\n' "$BASE" "$(basename "$f")" ;;
      esac
    done
  } >> "$GITHUB_STEP_SUMMARY"
fi
