// Inkjet syntax highlighting for Typst.
// Place inkjet.wasm next to this file and import this module.

#let _inkjet = plugin("inkjet.wasm")

/// Returns a native Typst raw-code element generated by WASM.
/// `eval` is used on trusted output generated by this plugin.
#let code(source, language: "rust") = {
  let generated = str(_inkjet.to_typst(bytes(language), bytes(source)))
  eval(generated)
}

/// Returns the generated Typst source without evaluating it.
#let code-source(source, language: "rust") = {
  str(_inkjet.to_typst(bytes(language), bytes(source)))
}

/// Returns a native Typst content value with Inkjet syntax colors.
#let highlighted-code(source, language: "rust") = {
  eval(str(_inkjet.to_typst_highlighted(bytes(language), bytes(source))))
}

/// Returns Inkjet's original class-based HTML output.
#let highlight-html(source, language: "rust") = {
  str(_inkjet.highlight(bytes(language), bytes(source)))
}

#let version() = str(_inkjet.version(bytes("")))
