// Generated by tools/gen_errno_table.py from kernel/errno.{h,c}. Do not edit.
//
// Guest numbers are the i386 Linux ABI from kernel/errno.h and do not move.
// Host numbers are whatever the generating platform calls them - this table
// was generated on Linux 6.1.158+, and a different host needs a different table, exactly
// as the C does. tools/gen_errno_table.py asks the host rather than assuming.
//
// 82 entries, 82 of which are the identity (host == -guest), 1 skipped as
// duplicates: ENOTSUP==EOPNOTSUPP.

/// `(host errno, guest errno)` in the order kernel/errno.c lists them.
pub const HOST_TO_GUEST: &[(i32, i32)] = &[
    (1, -1), // EPERM
    (2, -2), // ENOENT
    (3, -3), // ESRCH
    (4, -4), // EINTR
    (5, -5), // EIO
    (6, -6), // ENXIO
    (7, -7), // E2BIG
    (8, -8), // ENOEXEC
    (9, -9), // EBADF
    (10, -10), // ECHILD
    (11, -11), // EAGAIN
    (12, -12), // ENOMEM
    (13, -13), // EACCES
    (14, -14), // EFAULT
    (15, -15), // ENOTBLK
    (16, -16), // EBUSY
    (17, -17), // EEXIST
    (18, -18), // EXDEV
    (19, -19), // ENODEV
    (20, -20), // ENOTDIR
    (21, -21), // EISDIR
    (22, -22), // EINVAL
    (23, -23), // ENFILE
    (24, -24), // EMFILE
    (25, -25), // ENOTTY
    (26, -26), // ETXTBSY
    (27, -27), // EFBIG
    (28, -28), // ENOSPC
    (29, -29), // ESPIPE
    (30, -30), // EROFS
    (31, -31), // EMLINK
    (32, -32), // EPIPE
    (33, -33), // EDOM
    (34, -34), // ERANGE
    (35, -35), // EDEADLK
    (36, -36), // ENAMETOOLONG
    (37, -37), // ENOLCK
    (38, -38), // ENOSYS
    (39, -39), // ENOTEMPTY
    (40, -40), // ELOOP
    (60, -60), // ENOSTR
    (61, -61), // ENODATA
    (62, -62), // ETIME
    (63, -63), // ENOSR
    (66, -66), // EREMOTE
    (67, -67), // ENOLINK
    (71, -71), // EPROTO
    (72, -72), // EMULTIHOP
    (74, -74), // EBADMSG
    (75, -75), // EOVERFLOW
    (84, -84), // EILSEQ
    (87, -87), // EUSERS
    (88, -88), // ENOTSOCK
    (89, -89), // EDESTADDRREQ
    (90, -90), // EMSGSIZE
    (91, -91), // EPROTOTYPE
    (92, -92), // ENOPROTOOPT
    (93, -93), // EPROTONOSUPPORT
    (94, -94), // ESOCKTNOSUPPORT
    (95, -95), // EOPNOTSUPP
    (96, -96), // EPFNOSUPPORT
    (97, -97), // EAFNOSUPPORT
    (98, -98), // EADDRINUSE
    (99, -99), // EADDRNOTAVAIL
    (100, -100), // ENETDOWN
    (101, -101), // ENETUNREACH
    (102, -102), // ENETRESET
    (103, -103), // ECONNABORTED
    (104, -104), // ECONNRESET
    (105, -105), // ENOBUFS
    (106, -106), // EISCONN
    (107, -107), // ENOTCONN
    (108, -108), // ESHUTDOWN
    (109, -109), // ETOOMANYREFS
    (110, -110), // ETIMEDOUT
    (111, -111), // ECONNREFUSED
    (112, -112), // EHOSTDOWN
    (113, -113), // EHOSTUNREACH
    (114, -114), // EALREADY
    (115, -115), // EINPROGRESS
    (116, -116), // ESTALE
    (122, -122), // EDQUOT
];

/// The host's `EPIPE`. `errno_map` raises SIGPIPE on it, so the port has to
/// recognise it by the host's number, not the guest's.
pub const HOST_EPIPE: i32 = 32;
