project:
  type: book
  output-dir: _site

book:
  title: "xv6 RISC-V: ترجمة عربية أكاديمية"
  author: "روس كوكس ، فرانس كاشوك ، روبيرت موريس"
  date: "2026-09-08"
  dir: rtl
  language: ar
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd
    - chapters/01_unix.qmd
    - chapters/02_first.qmd
    - chapters/03_mem.qmd
    - chapters/04_trap.qmd
    - chapters/05_pgfault.qmd
    - chapters/06_interrupt.qmd
    - chapters/07_lock.qmd
    - chapters/08_sched.qmd
    - chapters/09_sleep.qmd
    - chapters/10_fs.qmd
    - chapters/11_log.qmd
    - chapters/12_lock2.qmd
    - chapters/13_sum.qmd

format:
  html:
    theme: cosmo
    code-copy: true
    toc: true
    number-sections: true

lang: ar
dir: rtl
