// Generated from the SICP XML sources by tools/convert.py — do not edit.
#import "../../../lib/sicp.typ": *

#subsection([Compiling Applications and Return Statements], label-name: <sec:compiling-combinations>)

#idx("compiler for Python", sub: "function applications")
#idx("compiler for Python", sub: "combinations")

The essence of the compilation process is the compilation of
function
applications. The code for
an application
compiled with a given target and
linkage has the form

#syntax(metaphrase[compilation of function expression, target #py("fun"), linkage #py("\"next\"")], "
", metaphrase[evaluate argument expressions and construct argument list in #py("argl")], "
", metaphrase[compilation of function call with given target and linkage])

The registers #py("env"),
#py("fun"),
and #py("argl") may
have to be saved and restored during evaluation of the
function and argument expressions.
Note that this is the only place in the compiler where a target other
than #py("val") is specified.

The required code is generated by
#py("compile_application").
This recursively compiles the
function expression,
to produce code that puts the
function
to be applied into
#py("fun"),
and compiles the
argument expressions,
to produce code that evaluates the individual
argument expressions
of the
application. The instruction sequences for the
argument expressions
are combined
(by
#py("construct_arglist"))
with code that constructs the list of
arguments in #py("argl"), and the resulting
argument-list code is combined with the
function
code and the code that performs the
function
call (produced by
#py("compile_function_call")).
In appending the code sequences, the #py("env")
register must be preserved around the evaluation of the
function expression
(since
evaluating the
function expression
might modify #py("env"), which
will be needed to evaluate the
argument expressions),
and the
#py("fun")
register must be preserved around the
construction of the argument list (since evaluating the
argument expressions
might
modify
#py("fun"),
which will be needed for the actual
function
application). The #py("continue") register
must also be preserved throughout, since
it is needed for the linkage in the
function
call.
#idx("compileapplication", decl: true)
#snippet(```python
function compile_application(exp, target, linkage) {
    const fun_code = compile(function_expression(exp), "fun", "next");
    const argument_codes = map(arg => compile(arg, "val", "next"),
                               arg_expressions(exp));
    return preserving(list("env", "continue"),
                      fun_code,
                      preserving(list("fun", "continue"),
                          construct_arglist(argument_codes),
                          compile_function_call(target, linkage)));
}
```)

The code to construct the argument list will evaluate each
argument expression
into
#py("val") and then
combine that value with the argument list being accumulated in #py("argl") using #py("pair").
Since we
adjoin the arguments to the front of #py("argl") in sequence,
we must start with the last argument and end with the first, so that the
arguments will appear in order from first to last in the resulting list.
Rather than waste an instruction by initializing
#py("argl") to the empty list
to set up for this sequence of evaluations,
we make the first code sequence construct the initial
#py("argl").
The general form of the argument-list construction is thus as follows:

#syntax(metaphrase[compilation of last argument, targeted to #py("val")], "
assign(\"argl\", list(op(\"list\"), reg(\"val\"))),
", metaphrase[compilation of next argument, targeted to #py("val")], "
assign(\"argl\", list(op(\"pair\"), reg(\"val\"), reg(\"argl\"))),
", $dots.h$, "
", metaphrase[compilation of first argument, targeted to #py("val")], "
assign(\"argl\", list(op(\"pair\"), reg(\"val\"), reg(\"argl\"))),
      ")

The #py("argl") register must be preserved around each argument
evaluation except the first (so that arguments accumulated so far
won't be lost), and #py("env") must be
preserved around each
argument evaluation except the last (for use by subsequent argument evaluations).

Compiling this argument code is a bit tricky, because of the special
treatment of the first
argument expression
to be evaluated and the need to preserve
#py("argl") and #py("env") in
different places. The
#py("construct_arglist")
function
takes as arguments the code that evaluates the individual
argument expressions.
If there are no
argument expressions
at all, it simply emits the instruction

#snippet(```python
assign(argl, constant(null))
```)

Otherwise,
#py("construct_arglist")
creates code that initializes #py("argl") with the
last argument, and appends code that evaluates the rest of the arguments and
adjoins them to #py("argl") in succession. In order
to process the arguments from last to first, we must reverse the list of
argument
code sequences from the order supplied by
#py("compile_application").
#idx("constructarglist", decl: true)
#snippet(```python
function construct_arglist(arg_codes) {
    if (is_null(arg_codes)) {
        return make_instruction_sequence(null, list("argl"),
                   list(assign("argl", constant(null))));
    } else {
        const rev_arg_codes = reverse(arg_codes);
        const code_to_get_last_arg =
            append_instruction_sequences(
                head(rev_arg_codes),
                make_instruction_sequence(list("val"), list("argl"),
                    list(assign("argl",
                                list(op("list"), reg("val"))))));
        return is_null(tail(rev_arg_codes))
               ? code_to_get_last_arg
               : preserving(list("env"),
                     code_to_get_last_arg,
                     code_to_get_rest_args(tail(rev_arg_codes)));
    }
}
function code_to_get_rest_args(arg_codes) {
    const code_for_next_arg =
        preserving(list("argl"),
            head(arg_codes),
            make_instruction_sequence(list("val", "argl"), list("argl"),
                list(assign("argl", list(op("pair"),
                                         reg("val"), reg("argl"))))));
    return is_null(tail(arg_codes))
           ? code_for_next_arg
           : preserving(list("env"),
                        code_for_next_arg,
                        code_to_get_rest_args(tail(arg_codes)));
}
```)

#subheading([Applying functions])

After evaluating the elements of a
function application,
the compiled code must apply the
function
in
#py("fun")
to the arguments in
#py("argl"). The code performs essentially the same
dispatch as the #py("apply")
function
in the metacircular evaluator of
section @sec:core-of-evaluator or the
#py("apply_dispatch")
entry point in the explicit-control evaluator of
section @sec:procedure-application. It checks whether
the
function
to be applied is a primitive
function
or a compiled
function.
For a primitive
function,
it uses
#py("apply_primitive_function");
we will see shortly how it handles compiled
functions.
The
function-application
code has the following form:

#syntax($mono(" ")mono(" ")$, "test(list(op(\"primitive_function\"), reg(\"fun\"))),
  branch(label(\"primitive_branch\")),
\"compiled_branch\",
  ", metaphrase[code to apply compiled function with given target and appropriate linkage], "
\"primitive_branch\",
  assign(", meta("target"), ",
         list(op(\"apply_primitive_function\"), reg(\"fun\"), reg(\"argl\"))),
  ", metaphrase[linkage], "
\"after_call\"
      ")

Observe that the compiled branch must skip around the primitive
branch. Therefore, if the linkage for the original
function
call was
#py("\"next\""),
the compound branch must use a
linkage that jumps to a label that is inserted after the primitive branch.
(This is similar to the linkage used for the true branch in
#py("compile_conditional").)
#idx("compilefunctioncall", decl: true)
#snippet(```python
function compile_function_call(target, linkage) {
    const primitive_branch = make_label("primitive_branch");
    const compiled_branch = make_label("compiled_branch");
    const after_call = make_label("after_call");
    const compiled_linkage = linkage === "next" ? after_call : linkage;
    return append_instruction_sequences(
        make_instruction_sequence(list("fun"), null,
            list(test(list(op("is_primitive_function"), reg("fun"))),
                 branch(label(primitive_branch)))),
        append_instruction_sequences(
            parallel_instruction_sequences(
                append_instruction_sequences(
                    compiled_branch,
                    compile_fun_appl(target, compiled_linkage)),
                append_instruction_sequences(
                    primitive_branch,
                    end_with_linkage(linkage,
                        make_instruction_sequence(list("fun", "argl"),
                                                  list(target),
                            list(assign(
                                   target,
                                   list(op("apply_primitive_function"),
                                        reg("fun"), reg("argl")))))))),
            after_call));
}
```)

The primitive and compound branches, like the true
and false branches in
#py("compile_conditional"),
are appended using
#py("parallel_instruction_sequences")
rather than the ordinary
#py("append_instruction_sequences"),
because they will not be executed sequentially.

#subheading([Applying compiled functions])

The handling of function
application
and return
is the most subtle part of the
compiler.
A compiled
function
(as constructed by
#py("compile_lambda_expression"))
has an entry point, which is a label that designates where the code for the
function
starts. The code at this entry point computes a result in
#py("val")
and ends by executing the instructions from a compiled return statement.

The code for a compiled-function application uses the
stack in the same way as the explicit-control evaluator
(section @sec:procedure-application):
before jumping to the compiled function's entry point, it
saves the continuation of the function call to the stack,
followed by a mark that allows reverting the stack to the
state right before the call with the continuation on top.

#syntax($mono(" ")mono(" ")$, "// set up for return from function
  save(\"continue\"),
  push_marker_to_stack(),
  // jump to the function's entry point
  assign(\"val\", list(op(\"compiled_function_entry\"), reg(\"fun\"))),
  go_to(reg(\"val\")),
        ")

Compiling a return statement (with
#py("compile_return_statement"))
generates corresponding code for reverting the stack and restoring
and jumping to #py("continue").

#syntax($mono(" ")mono(" ")$, "revert_stack_to_marker(),
  restore(\"continue\"),
  ", metaphrase[evaluate the return expression and store the result in #py("val")], "
  go_to(reg(\"continue\")), // ", $mono("\"return\"")$, "-linkage code
         ")

Unless a function enters an infinite loop,
it will end by executing the above return code,
resulting from either a return statement in the program
or one inserted by #py("compile_lambda_body")
#idx("return value", sub: "undefined as")
to return #py("undefined").#footnote[Because the execution of a function body always ends with a return,
there is no need here for a mechanism like the #py("return_undefined")
entry point from section @sec:procedure-application.]

Straightforward code for a compiled-function application with a
given target and linkage would set up #py("continue") to make the function
return to a local label instead of to the final linkage,
to copy the function value from #py("val") to the target register if necessary.
It would look like this if the linkage is a label:

#syntax($mono(" ")mono(" ")$, "assign(\"continue\", label(\"fun_return\")), // where function should return to
  save(\"continue\"),       // will be restored by the function
  push_marker_to_stack(), // allows the function to revert stack to find ", $mono("fun_return")$, "
  assign(\"val\", list(op(\"compiled_function_entry\"), reg(\"fun\"))),
  go_to(reg(\"val\")),    // eventually reverts stack, restores and jumps to ", $mono("continue")$, "
\"fun_return\",             // the function returns to here
  assign(", $italic("target")$, ", reg(\"val\")), // included if target is not ", $mono("val")$, "
  go_to(label(", meta("linkage"), ")),   // linkage code
      ")

or like
this—saving the caller's continuation at the start in order to restore and go to it at the end—if the linkage is #py("\"return\"") (that is, if the application is in a return statement and its value is the result to be returned):

#syntax($mono(" ")mono(" ")$, "save(\"continue\"),       // save the caller's continuation
  assign(\"continue\", label(\"fun_return\")), // where function should return to
  save(\"continue\"),       // will be restored by the function
  push_marker_to_stack(), // allows the function to revert stack to find ", $mono("fun_return")$, "
  assign(\"val\", list(op(\"compiled_function_entry\"), reg(\"fun\"))),
  go_to(reg(\"val\")),    // eventually reverts stack, restores and jumps to ", $mono("continue")$, "
\"fun_return\",             // the function returns to here
  assign(", $italic("target")$, ", reg(\"val\")), // included if target is not ", $mono("val")$, "
  restore(\"continue\"),    // restore the caller's continuation
  go_to(reg(\"continue\")), // linkage code
      ")

This code sets up #py("continue") so that the
function
will return to a label
#py("fun_return")
and jumps to the
function's
entry point. The code at
#py("fun_return")
transfers the
function's
result from #py("val") to the target register (if
necessary) and then jumps to the location specified by the linkage.
(The linkage is always
#py("\"return\"")
or a label,
because
#py("compile_function_call")
replaces a
#py("\"next\"")
linkage for the
compound-function branch by an #py("after_call")
label.)

Before jumping to the function's entry point, we
save #py("continue") and
execute #py("push_marker_to_stack()") to enable
the function to return to the intended location in the program with the expected stack. Matching
#py("revert_stack_to_marker()") and
#py("restore(\"continue\")") instructions
are generated by #py("compile_return_statement") for each return statement in the body of the
function.#footnote[Elsewhere in the compiler, all saves and restores of registers
are generated by #py("preserving")
to preserve a register's value across a sequence of instructions
by saving it before those instructions and restoring it
after—for example over the evaluation of the predicate of a
conditional. But this mechanism cannot generate instructions to
save and restore #py("continue") for a function application and the
corresponding return, because these are compiled separately and
are not contiguous. Instead, these saves and restores must be
explicitly generated by #py("compile_fun_appl") and
#py("compile_return_statement").]

In fact, if
the target is not #py("val"),
the above is
exactly the code our compiler will generate.#footnote[Actually, we signal
an error when the target is not #py("val") and the
linkage is
#py("\"return\""),
since the only place we request
a #py("\"return\"") linkage
is in compiling
return expressions,
and our convention is that
functions
return their values in #py("val").]
Usually, however, the target is #py("val") (the only
time the compiler specifies a different register is when targeting the
evaluation of
a function expression
to
#py("fun")),
so the
function
result is put directly into
the target register and there is no need to
jump
to a special
location that copies it. Instead we simplify the code by
setting up #py("continue") so that the
called function
will
"return"
directly to the place specified by the caller's linkage:

#syntax(metaphrase[set up #py("continue") for linkage and push the marker], "
assign(\"val\", list(op(\"compiled_function_entry\"), reg(\"fun\"))),
go_to(reg(\"val\")),
      ")

If the linkage is a label, we set up #py("continue")
so that the
function
will continue at
that label. (That is, the
#py("go_to(reg(\"continue\"))")
the
called function
ends with becomes equivalent to the
#py("go_to(label(")#meta("linkage")#py("))")
at
#py("fun_return")
above.)

#syntax("
assign(\"continue\", label(", meta("linkage"), ")),
save(\"continue\"),
push_marker_to_stack(),
assign(\"val\", list(op(\"compiled_function_entry\"), reg(\"fun\"))),
go_to(reg(\"val\")),
      ")

If the linkage is
#py("\"return\""),
we don't need to
assign #py("continue"):
It already holds the desired location.
(That is, the
#py("go_to(reg(\"continue\"))")
the
called function
ends with goes directly to the
place where the
#py("go_to(reg(\"continue\"))")
at
#py("fun_")#py-plain("return")
would have gone.)

#snippet(```python
save("continue"),
push_marker_to_stack(),
assign("val", list(op("compiled_function_entry"), reg("fun"))),
go_to(reg("val")),
```)

With this implementation of the
#py("\"return\"")
linkage,
the compiler generates
#idx("return statement", sub: "tail recursion and")
#idx("compiler for Python", sub: "tail-recursive code generated by")
#idx("tail recursion", sub: "compiler and")
tail-recursive code.
A function call in a return statement whose value is the result to be returned
does a direct transfer, without saving
unnecessary information on the stack.

Suppose instead that we had handled the case of a
function
call with a
linkage of #py("\"return\"") and a target of
#py("val") in the same way as for a
non-#py("val") target. This would destroy tail
recursion. Our system would still
return
function call.
But each time we called a
function,
we would save
#py("continue")
and return after the call to undo the (useless) save. These extra
saves would accumulate during a nest of
function
calls.#footnote[Making a
#idx("compiler", sub: "tail recursion, stack allocation, and garbage-collection")
compiler generate tail-recursive
code is desirable, especially in the functional paradigm.
However, compilers for common languages,
including
C and C++,
do not always do this, and therefore these languages
cannot represent iterative processes in terms of
function
call alone. The difficulty with
#idx("tail recursion", sub: "garbage collection and")
#idx("garbage collection", sub: "tail recursion and")
#idx("stack allocation and tail recursion")
tail recursion in these languages is that their
implementations use the stack to store
function
arguments and local
names
as well as return addresses. The
Python
implementations described in this book store arguments and
names
in memory to be garbage-collected. The reason for using the stack for
names
and arguments is that it avoids the need for garbage collection
in languages that would not otherwise require it, and is generally
believed to be more efficient. Sophisticated

compilers can, in fact, use the stack for arguments without destroying tail
recursion. (See
#idx("Hanson, Christopher P.")
Hanson 1990 for a description.) There is also some
debate about whether stack allocation is actually more efficient than garbage
collection in the first place, but the details seem to hinge on fine
points of computer architecture. (See
#idx("Appel, Andrew W.")
Appel 1987 and
#idx("Miller, James S.")
#idx("Rozas, Guillermo Juan")
Miller and Rozas 1994
for opposing views on this issue.)]

The function #py("compile_fun_appl")
generates the above
function-application
code by considering four cases,
depending on whether the target for the call
is #py("val") and whether the linkage is
#py("\"return\"").
Observe that the instruction sequences
are declared to modify all the registers, since executing the
function
body can change the registers in arbitrary ways.#footnote[The
constant
#idx("compiler for Python", sub: "register use")
#py("all_regs")
is bound to the list of names of all the registers:
#idx("allregs (compiler)", decl: true)
#snippet(```python
const all_regs = list("env", "fun", "val", "argl", "continue");
```)]

#idx("compilefunappl", decl: true)
#syntax("
function compile_fun_appl(target, linkage) {
    const fun_return = make_label(\"fun_return\");
    return target === \"val\" && linkage !== \"return\"
           ? make_instruction_sequence(list(\"fun\"), all_regs,
                 list(assign(\"continue\", label(linkage)),
                      save(\"continue\"),
                      push_marker_to_stack(),
                      assign(\"val\", list(op(\"compiled_function_entry\"),
                                         reg(\"fun\"))),
                      go_to(reg(\"val\"))))
           : target !== \"val\" && linkage !== \"return\"
           ? make_instruction_sequence(list(\"fun\"), all_regs,
                 list(assign(\"continue\", label(fun_return)),
                      save(\"continue\"),
                      push_marker_to_stack(),
                      assign(\"val\", list(op(\"compiled_function_entry\"),
                                         reg(\"fun\"))),
                      go_to(reg(\"val\")),
                      fun_return,
                      assign(target, reg(\"val\")),
                      go_to(label(linkage))))
           : target === \"val\" && linkage === \"return\"
           ? make_instruction_sequence(list(\"fun\", \"continue\"),
                                       all_regs,
                 list(save(\"continue\"),
                      push_marker_to_stack(),
                      assign(\"val\", list(op(\"compiled_function_entry\"),
                                         reg(\"fun\"))),
                      go_to(reg(\"val\"))))
           : // ", $mono("target !== \"val\" && linkage === \"return\"")$, "
             error(target, \"return linkage, target not val -- compile\");
}
      ")

#idx("compiler for Python", sub: "function applications")
#idx("compiler for Python", sub: "combinations")

We have shown how to generate tail-recursive linkage code for a
function application when the linkage is #py("\"return\"")—that is, when the application is in a return statement
and its value is the result to be returned. Similarly, as explained in
section @sec:procedure-application, the stack-marker mechanism used here (and in the
explicit-control evaluator) for the call and return produces
#idx("return statement", sub: "tail recursion and")
#idx("tail recursion", sub: "return statement necessary for")
tail-recursive behavior only in that situation. These two aspects of the code generated for function
application combine to ensure that when a function ends by returning
the value of a function call, no stack accumulates.

#subheading([Compiling return statements])

The code for a
#idx("compiler for Python", sub: "return statements")
#idx("return statement", sub: "handling in compiler")
return statement takes the following form, regardless of the given linkage and target:

#syntax("
revert_stack_to_marker(),
restore(\"continue\"),   // saved by ", $mono("compile_fun_appl")$, "
", metaphrase[evaluate the return expression and store the result in #py("val")], "
go_to(reg(\"continue\")) // ", $mono("\"return\"")$, "-linkage code
          ")

The instructions to revert the stack using the marker and then restore
#py("continue") correspond to the
instructions generated by #py("compile_fun_appl")
to save #py("continue") and mark the stack.
The final jump to #py("continue") is
generated by the use of the #py("\"return\"")
linkage when compiling the return expression.
The function #py("compile_return_statement")
is different from all other code generators in that it ignores the target
and linkage arguments—it always compiles the return expression with
target #py("val") and linkage
#py("\"return\"").
#idx("compilereturnstatement", decl: true)
#snippet(```python
function compile_return_statement(stmt, target, linkage) {
    return append_instruction_sequences(
               make_instruction_sequence(null, list("continue"),
                   list(revert_stack_to_marker(),
                        restore("continue"))),
               compile(return_expression(stmt), "val", "return"));
}
```)
