#!/usr/bin/env python3
"""Derive src/errno_table.rs from iSH's kernel/errno.{h,c}.

The mapping has two halves that live in different places:

  * the *guest* numbers are the i386 Linux ABI, fixed by `#define _EXXX -n` in
    kernel/errno.h;
  * the *host* numbers are whatever the compiling platform calls them, and the C
    gets them from <errno.h> at build time.

So the host half cannot be transcribed - it has to be asked for. This script
emits a C program that prints every name in kernel/errno.c's ERRCASE list with
its host value, runs it, joins that against the guest values, and writes the
table. Regenerating on a different host produces that host's table, which is
exactly what the C does.

    ISH_SRC=/path/to/ish tools/gen_errno_table.py
"""
import os
import re
import subprocess
import sys

ISH_SRC = os.environ.get("ISH_SRC", "/tmp/ish-src")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "errno_table.rs")


def errcase_names():
    """The names kernel/errno.c maps, in the order it lists them."""
    src = open(os.path.join(ISH_SRC, "kernel", "errno.c")).read()
    names = re.findall(r"ERRCASE\((E[A-Z0-9]+)\)", src)
    if len(names) < 80:
        sys.exit("only found %d ERRCASEs (expected 83); is this kernel/errno.c?" % len(names))
    # kernel/errno.c guards ENOTSUP with `#if EOPNOTSUPP != ENOTSUP`; on hosts
    # where they are the same number the case does not exist. Dropping the
    # duplicate by value below handles both possibilities.
    return names


def guest_values():
    """_EXXX -> guest errno, resolving aliases like `#define _ENOTSUP _EOPNOTSUPP`."""
    defines = {}
    for line in open(os.path.join(ISH_SRC, "kernel", "errno.h")):
        m = re.match(r"#define\s+(_E[A-Z0-9]+)\s+(.+?)(?:\s*/\*.*)?$", line.strip())
        if m:
            defines[m.group(1)] = m.group(2).strip()

    def resolve(name, seen=()):
        if name in seen:
            sys.exit("cycle resolving %s" % name)
        text = defines.get(name)
        if text is None:
            sys.exit("kernel/errno.h has no %s" % name)
        m = re.match(r"^-?\d+$", text)
        if m:
            return int(text)
        return resolve(text, seen + (name,))

    return {name: resolve(name) for name in defines}


def host_values(names):
    """Ask the host what it calls each of these."""
    prog = ["#include <errno.h>", "#include <stdio.h>", "int main(void) {"]
    # errno_map() singles EPIPE out, so the port needs the host's number for it
    names = list(dict.fromkeys(names + ["EPIPE"]))
    for n in names:
        prog.append('    printf("%s %%d\\n", %s);' % (n, n))
    prog.append("    return 0;\n}")
    c = "/tmp/errno_host.c"
    open(c, "w").write("\n".join(prog) + "\n")
    subprocess.check_call(["cc", "-O0", "-w", "-o", "/tmp/errno_host", c])
    out = subprocess.check_output(["/tmp/errno_host"]).decode()
    values = {}
    for line in out.splitlines():
        name, value = line.split()
        values[name] = int(value)
    missing = [n for n in names if n not in values]
    if missing:
        sys.exit("host has no value for: %s" % ", ".join(missing))
    return values


def main():
    names = errcase_names()
    guest = guest_values()
    host = host_values(names)

    pairs = []
    seen_host = {}
    skipped = []
    for n in names:
        h = host[n]
        g = guest.get("_" + n)
        if g is None:
            sys.exit("%s is in kernel/errno.c but has no guest number" % n)
        if h in seen_host:
            # the `#if EOPNOTSUPP != ENOTSUP` case: same host number, so the C
            # has one case label, not two
            skipped.append((n, seen_host[h]))
            continue
        seen_host[h] = n
        pairs.append((h, g, n))

    identity = sum(1 for h, g, _ in pairs if h == -g)
    uname = subprocess.check_output(["uname", "-sr"]).decode().strip()

    lines = [
        "// Generated by tools/gen_errno_table.py from kernel/errno.{h,c}. Do not edit.",
        "//",
        "// Guest numbers are the i386 Linux ABI from kernel/errno.h and do not move.",
        "// Host numbers are whatever the generating platform calls them - this table",
        "// was generated on %s, and a different host needs a different table, exactly" % uname,
        "// as the C does. tools/gen_errno_table.py asks the host rather than assuming.",
        "//",
        "// %d entries, %d of which are the identity (host == -guest), %d skipped as" % (
            len(pairs), identity, len(skipped)),
        "// duplicates: %s." % (", ".join("%s==%s" % s for s in skipped) or "none"),
        "",
        "/// `(host errno, guest errno)` in the order kernel/errno.c lists them.",
        "pub const HOST_TO_GUEST: &[(i32, i32)] = &[",
    ]
    for h, g, n in pairs:
        lines.append("    (%d, %d), // %s" % (h, g, n))
    lines += [
        "];",
        "",
        "/// The host's `EPIPE`. `errno_map` raises SIGPIPE on it, so the port has to",
        "/// recognise it by the host's number, not the guest's.",
        "pub const HOST_EPIPE: i32 = %d;" % host["EPIPE"],
        "",
    ]
    open(OUT, "w").write("\n".join(lines))
    print("wrote %s: %d entries (%d identity, %d skipped as duplicates)"
          % (os.path.normpath(OUT), len(pairs), identity, len(skipped)))


if __name__ == "__main__":
    main()
