// Reference-output generator for the random differential test.
//
// Links the *unmodified* kernel/random.c. Its Linux get_random() reaches the
// host through libc's syscall(SYS_getrandom, ...); the linker's --wrap=syscall
// hook below supplies deterministic bytes and failures while still executing
// the C implementation's allocation, limit check, failure mapping, and guest
// write ordering.

#define _GNU_SOURCE

#include <assert.h>
#include <errno.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>

#include "kernel/calls.h"

#define GUEST_BASE ((addr_t) 0x001000)
#define GUEST_SIZE ((size_t) 0x002000)
#define A0 ((addr_t) 0x001000)
#define A1 ((addr_t) 0x001040)
#define A2 ((addr_t) 0x001100)
#define LAST ((addr_t) 0x002fff)
#define BAD ((addr_t) 0x009000)

static byte_t guest[GUEST_SIZE];
static bool source_fails;
static unsigned source_calls;

// This substitutes only the OS boundary inside random.c's own get_random().
// The generated byte formula is duplicated by the Rust test source.
long __wrap_syscall(long number, ...) {
    va_list args;
    va_start(args, number);
    char *buf = va_arg(args, char *);
    size_t len = va_arg(args, size_t);
    int flags = va_arg(args, int);
    va_end(args);

    if (number != SYS_getrandom || flags != 0)
        abort();
    unsigned call = source_calls++;
    if (source_fails) {
        errno = EIO;
        return -1;
    }
    for (size_t i = 0; i < len; i++)
        buf[i] = (char) ((i * 29 + len + call * 17) & 0xff);
    return (long) len;
}

static bool guest_range(addr_t addr, size_t count) {
    if (count == 0)
        return true;
    if (addr < GUEST_BASE)
        return false;
    size_t offset = (size_t) (addr - GUEST_BASE);
    return offset <= GUEST_SIZE && count <= GUEST_SIZE - offset;
}

int user_write(addr_t addr, const void *buf, size_t count) {
    if (!guest_range(addr, count))
        return 1;
    if (count != 0)
        memcpy(&guest[addr - GUEST_BASE], buf, count);
    return 0;
}

// random.c does not reach these in this corpus, but calls.h/debug may retain
// their symbols under a non-default tracing build.
int current_pid(void) { return 1; }
_Noreturn void die(const char *msg, ...) {
    va_list args;
    va_start(args, msg);
    vfprintf(stderr, msg, args);
    va_end(args);
    abort();
}
void ish_printk(const char *msg, ...) { (void) msg; }

static uint64_t guest_hash(void) {
    uint64_t hash = UINT64_C(0xcbf29ce484222325);
    for (size_t i = 0; i < GUEST_SIZE; i++) {
        hash ^= guest[i];
        hash *= UINT64_C(0x100000001b3);
    }
    return hash;
}

static void snapshot(void) {
    printf("S %08x %016llx\n", source_calls,
           (unsigned long long) guest_hash());
}

static void prep_fail(bool fail) {
    source_fails = fail;
    printf("P FAIL %u\n", fail);
}

#define OP(...) \
    do { \
        printf("O "); \
        printf(__VA_ARGS__); \
        putchar('\n'); \
    } while (0)

static void call_getrandom(addr_t addr, dword_t len, dword_t flags) {
    OP("GR %08x %08x %08x", addr, len, flags);
    printf("R %08x\n", sys_getrandom(addr, len, flags));
    snapshot();
}

int main(void) {
    for (size_t i = 0; i < GUEST_SIZE; i++)
        guest[i] = (byte_t) ((i * 31 + 7) & 0xff);

    printf("# random reference output, generated from unmodified iSH kernel/random.c\n");
    printf("# syscall(SYS_getrandom) is linker-wrapped with deterministic bytes/failures\n");
    printf("# S: source call count and FNV-1a of the full two-page guest window\n");
    prep_fail(false);
    snapshot();

    // Zero length still asks the host source and performs a zero-byte user write.
    call_getrandom(A0, 0, 0);
    call_getrandom(A0, 1, 0);
    // The C implementation accepts but ignores getrandom flags.
    call_getrandom(A1, 17, 0xffffffffu);
    // Host bytes are obtained before a guest-output fault.
    call_getrandom(BAD, 8, 0);
    prep_fail(true);
    call_getrandom(A2, 32, 0);
    prep_fail(false);
    // Exactly one MiB is accepted before its attempted guest write faults. Use
    // an unmapped start address, rather than a partial two-page overlap: the
    // real user-copy partial-write behavior is covered by user-dump.c.
    call_getrandom(BAD, 1u << 20, 0);
    // One byte above the bound returns EIO before asking the source.
    call_getrandom(A2, (1u << 20) + 1, 0);
    // A whole guest window and its final byte test output boundaries.
    call_getrandom(A0, GUEST_SIZE, 0x12345678u);
    call_getrandom(LAST, 1, 0);

    return 0;
}
