package wasmjit

import "github.com/mostafa637/mostafa637/go-pure/internal/core/cpu/machinecode"

func wideMulU(inst machinecode.Instruction) []byte {
	var out []byte
	out = append(out, localCode(0)...)
	out = append(out, constCode(0xffffffff)...)
	out = append(out, WasmOpI64And, WasmOpLocalSet, 19)
	out = append(out, localCode(0)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64ShrU, WasmOpLocalSet, 20)
	out = append(out, localCode(18)...)
	out = append(out, constCode(0xffffffff)...)
	out = append(out, WasmOpI64And, WasmOpLocalSet, 21)
	out = append(out, localCode(18)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64ShrU, WasmOpLocalSet, 22)
	out = append(out, localCode(19)...)
	out = append(out, localCode(21)...)
	out = append(out, WasmOpI64Mul, WasmOpLocalSet, 23)
	out = append(out, localCode(20)...)
	out = append(out, localCode(21)...)
	out = append(out, WasmOpI64Mul, WasmOpLocalSet, 24)
	out = append(out, localCode(19)...)
	out = append(out, localCode(22)...)
	out = append(out, WasmOpI64Mul, WasmOpLocalSet, 25)
	out = append(out, localCode(20)...)
	out = append(out, localCode(22)...)
	out = append(out, WasmOpI64Mul, WasmOpLocalSet, 26)
	out = append(out, localCode(23)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64ShrU)
	out = append(out, localCode(24)...)
	out = append(out, constCode(0xffffffff)...)
	out = append(out, WasmOpI64And, WasmOpI64Add)
	out = append(out, localCode(25)...)
	out = append(out, constCode(0xffffffff)...)
	out = append(out, WasmOpI64And, WasmOpI64Add, WasmOpLocalSet, 19)
	out = append(out, localCode(23)...)
	out = append(out, constCode(0xffffffff)...)
	out = append(out, WasmOpI64And)
	out = append(out, localCode(19)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64Shl, WasmOpI64Or, WasmOpLocalSet, 0)
	out = append(out, localCode(26)...)
	out = append(out, localCode(24)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64ShrU, WasmOpI64Add)
	out = append(out, localCode(25)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64ShrU, WasmOpI64Add)
	out = append(out, localCode(19)...)
	out = append(out, constCode(32)...)
	out = append(out, WasmOpI64ShrU, WasmOpI64Add, WasmOpLocalSet, 2)
	return out
}
