// Generated from the SICP XML sources by tools/convert.py — do not edit.
#import "../../lib/sicp.typ": *

#idx("=>", sort: "0a1", see-also: "lambda expression")
#idx("? :", sort: ";3", see-also: "conditional expression")
#idx("π", sort: "0p", see: "pi")
#idx("=", sort: "=", see-also: "assignment")
#idx("abstract data", see-also: "data abstraction")
#idx("abstraction", see-also: "data abstraction; higher-order functions; means of abstraction")
#idx("agenda", see: "digital-circuit simulation")
#idx("algebra, symbolic", see: "symbolic algebra")
#idx("amb evaluator", sort: "amb eval", see: "nondeterministic evaluator")
#idx("argument passing", see: "call-by-name argument passing; call-by-need argument passing")
#idx("arithmetic", sub: "generic", see-also: "generic arithmetic operations")
#idx("arithmetic", sub: "on polynomials", see: "polynomial arithmetic")
#idx("array", see: "vector (data structure)")
#idx("arrow function", see: "lambda expression")
#idx("automatic search", see-also: "search")
#idx("backtracking", see-also: "nondeterministic computing")
#idx("balanced binary tree", see-also: "binary tree")
#idx("binary numbers, addition of", see: "adder")
#idx("break (keyword)", sort: "break", see-also: "while loop")
#idx("case analysis", see-also: "conditional expression")
#idx("changing money", see: "counting change")
#idx("circuit", sub: "digital", see: "digital-circuit simulation")
#idx("code", sub: "Huffman", see: "Huffman code")
#idx("combination", see-also: "function application; operator combination")
#idx("combination, means of", see-also: "closure")
#idx("compound expression", see-also: "function application; operator combination; syntactic form")
#idx("compilation", see: "compiler")
#idx("compiler for Python", sub: "code generators", see: "compile…")
#idx("compiler for Python", see-also: "code generator; compile-time environment; instruction sequence; linkage descriptor; target register")
#idx("compound function", see-also: "function")
#idx("computational process", see-also: "process")
#idx("conditional expression", see-also: "case analysis")
#idx("conjunction", see-also: "&& (logical conjunction)")
#idx("const (keyword)", sort: "const", see-also: "constant declaration")
#idx("continuation", sub: "in nondeterministic evaluator", see-also: "failure continuation; success continuation")
#idx("continue (keyword)", sort: "continue", see-also: "while loop")
#idx("controller for register machine", see-also: "register-machine language")
#idx("data", sub: "abstract", see-also: "data abstraction")
#idx("data", sub: "mutable", see: "mutable data objects")
#idx("data abstraction", see-also: "metacircular evaluator")
#idx("declaration", see-also: "internal declaration")
#idx("differential equation", see-also: "solve")
#idx("disjunction", see-also: "\"|\"| (logical disjunction)")
#idx("dispatching", sub: "on type", see-also: "data-directed programming")
#idx("efficiency", see-also: "order of growth")
#idx("else (keyword)", sort: "else", see-also: "conditional statement")
#idx("empty list", see-also: "nullnull")
#idx("environment", sub: "compile-time", see: "compile-time environment")
#idx("environment", sub: "global", see: "global environment")
#idx("environment", sub: "program", see: "program environment")
#idx("equation, solving", see: "half-interval method; Newton's method; solve")
#idx("Euclid's Algorithm", see-also: "greatest common divisor")
#idx("evaluation", sub: "applicative-order", see: "applicative-order evaluation")
#idx("evaluation", sub: "normal-order", see: "normal-order evaluation")
#idx("evaluation", sub: "order of subexpression evaluation", see: "order of evaluation")
#idx("evaluation", sub: "delayed", see: "delayed evaluation")
#idx("evaluation", sub: "environment model of", see: "environment model of evaluation")
#idx("evaluation", sub: "substitution model of", see: "substitution model of function application")
#idx("evaluator", see-also: "interpreter")
#idx("evaluators", see: "metacircular evaluator; analyzing evaluator; lazy evaluator; nondeterministic evaluator; query interpreter; explicit-control evaluator")
#idx("expression", sub: "algebraic", see: "algebraic expressions")
#idx("expression", see-also: "compound expression; primitive expression")
#idx("expression", sub: "symbolic", see-also: "string(s); symbol(s)")
#idx("factorial", see-also: "factorial")
#idx("Fibonacci numbers", see-also: "fib")
#idx("Fibonacci numbers", sub: "infinite stream of", see: "fibs")
#idx("formal parameters", see: "parameters")
#idx("fraction", see: "rational number(s)")
#idx("frame (query interpreter)", see-also: "pattern matching; unification")
#idx("function (keyword)", sort: "function", see-also: "function definition")

#idx("function application", sub: "substitution model of", see: "substitution model of function application")
#idx("GCD", see: "greatest common divisor")
#idx("generic types", see: "polymorphic types")
#idx("graphics", see: "picture language")
#idx("greatest common divisor", see-also: "gcd")
#idx("``how to'' vs. ``what is'' description", sort: "how to", see: "imperative vs.declarative knowledge")
#idx("if (keyword)", sort: "if", see-also: "conditional statement")
#idx("infinite stream(s)", sub: "of integers", see: "integers")
#idx("infinite stream(s)", sub: "of Fibonacci numbers", see: "fibs")
#idx("infinite stream(s)", sub: "of prime numbers", see: "primes")
#idx("information retrieval", see: "data base")
#idx("integral", see-also: "definite integral; Monte Carlo integration")
#idx("interpreter", see-also: "evaluator")
#idx("iteration contructs", see: "looping constructs")
#idx("iterative process", sub: "implemented by function call", see-also: "tail recursion")
#idx("language", see: "parsing natural language; programming language")
#idx("let (keyword)", sort: "let", see-also: "variable, declaration")
#idx("lexical scoping", see-also: "scope of a name")
#idx("LIFO buffer", see: "stack")
#idx("Lisp", see-also: "Scheme")
#idx("list(s)", see-also: "list structure")
#idx("list(s)", sub: "empty", see: "empty list")
#idx("list structure", see-also: "list(s)")
#idx("logic programming", see-also: "query interpreter; query language")
#idx("logical conjunction", see-also: "&& (logical conjunction)")
#idx("logical disjunction", see-also: "\"|\"| (logical disjunction)")
#idx("looping constructs", see-also: "while loop")
#idx("magician", see: "numerical analyst")
#idx("making change", see: "counting change")
#idx("mathematical function", see: "function (mathematical)")
#idx("means of combination", see-also: "closure")
#idx("merging infinite streams", see: "infinite stream(s)")
#idx("modified registers", see: "instruction sequence")
#idx("money, changing", see: "counting change")
#idx("mutable data objects", see-also: "queue; table")
#idx("name", see: "constant; local name; variable")
#idx("name", sub: "scope of", see-also: "scope of a name")
#idx("natural language parsing", see: "parsing natural language")
#idx("needed registers", see: "instruction sequence")
#idx("nested declaration(s)", see: "internal declaration")
#idx("nested mapping(s)", see: "mapping")
#idx("normal-order evaluator", see: "lazy evaluator")
#idx("operator precedence", see: "precedence")
#idx("order of subexpression evaluation", see: "order of evaluation")
#idx("parameter passing", see: "call-by-name argument passing; call-by-need argument passing")
#idx("parse", see-also: "parsing Python")
#idx("prime number(s)", sub: "infinite stream of", see: "primes")
#idx("primitive query", see: "simple query")
#idx("program", sub: "structure of", see-also: "abstraction barriers")
#idx("programming", sub: "data-directed", see: "data-directed programming")
#idx("programming", sub: "functional", see: "functional programming")
#idx("query", see-also: "compound query; simple query")
#idx("query language", sub: "simple query", see: "simple query")
#idx("query language", sub: "compound query", see: "compound query")
#idx("query language", sub: "rule", see: "rule")
#idx("query interpreter", sub: "simple query", see: "simple query")
#idx("query interpreter", sub: "compound query", see: "compound query")
#idx("query interpreter", sub: "rule", see: "rule")
#idx("read-evaluate-print loop", see-also: "driver loop")
#idx("return (keyword)", sort: "return", see-also: "return statement")

#idx("roots of equation", see: "half-interval method; Newtons method")
#idx("scope of a name", see-also: "lexical scoping")
#idx("simulation", sub: "Monte Carlo", see: "Monte Carlo simulation")
#idx("simulation", sub: "of digital circuit", see: "digital-circuit simulation")
#idx("solving equation", see: "half-interval method; Newtons method; solve")
#idx("square root", see-also: "sqrt")
#idx("state", sub: "local", see: "local state")
#idx("statement sequence", see: "sequence of statements")
#idx("stream(s)", sub: "infinite", see: "infinite streams")
#idx("string(s)", sub: "quotation marks for", see: "quotation marks")
#idx("symbolic expression", see-also: "string(s); symbol(s)")
#idx("synchronization", see: "concurrency")
#idx("syntax", sub: "abstract", see: "abstract syntax")
#idx("syntax", see-also: "syntactic form")
#idx("table", sub: "operation-and-type", see: "operation-and-type table")
#idx("temporal dead zone (TDZ)", see-also: "declaration, use of name before")
#idx("TDZ (temporal dead zone)", see-also: "declaration, use of name before")
#idx("ternary operator", see: "conditional expression")
#idx("tree", sub: "binary", see-also: "binary tree")
#idx("``what is'' vs. ``how to'' description", sort: "what is", see: "declarative vs.imperative knowledge")
#idx("while (keyword)", sort: "while", see-also: "while loop")
