// Generated from the SICP XML sources by tools/convert.py — do not edit.
#import "../../../lib/sicp.typ": *

#subsection([The Machine Model], label-name: <sec:machine-model>)

The machine model generated by
#py("make_machine")
is represented as a
function
with local state using the message-passing techniques
developed in chapter @chap:state. To build this model,
#py("make_machine")
begins by calling the
function
#py("make_new_machine")
to construct
the parts of the machine model that are common to all register
machines. This basic machine model constructed by
#py("make_new_machine")
is essentially a container for some registers and a stack, together with an
execution mechanism that processes the controller instructions one by one.

The function #py("make_machine")
then extends this basic model (by sending it
messages) to include the registers, operations, and controller of the
particular machine being defined. First it allocates a register in
the new machine for each of the supplied register names and installs
the designated operations in the machine. Then it uses an
#idx("assembler")
#emph[assembler] (described below in
section @sec:assembler) to transform the controller list
into instructions for the new machine and installs these as the
machine's instruction sequence.
The function #py("make_machine")
returns as its value the modified machine model.

#idx("makemachine", decl: true)
#snippet(```python
def make_machine(register_names, ops, controller):
    machine = make_new_machine()
    for_each(lambda register_name: machine("allocate_register")(register_name),
             register_names)
    machine("install_operations")(ops)
    machine("install_instruction_sequence")(assemble(controller, machine))
    return machine
```)

#subheading([Registers])

#idx("register(s)", sub: "representing")

We will represent a register as a
function
with local state, as in
chapter @chap:state. The
function
#py("make_register") creates a register that
holds a value that can be accessed or changed:
#idx("makeregister", decl: true)
#snippet(```python
def make_register(name):
    contents = "*unassigned*"
    def dispatch(message):
        def set_value(value):
            nonlocal contents
            contents = value
        return (contents if message == "get"
                else set_value if message == "set"
                else error("unknown request -- make_register", message))
    return dispatch
```)

The following
functions
are used to access registers:
#idx("getcontents", decl: true)#idx("setcontents", decl: true)
#snippet(```python
def get_contents(register):
    return register("get")
def set_contents(register, value):
    return register("set")(value)
```)

#subheading([The stack])

#idx("stack", sub: "representing")

We can also represent a stack as a
function
with local state. The
function
#py("make_stack")
creates a stack whose local state consists
of a list of the items on the stack. A stack accepts requests to
#py("push") an item onto the stack, to
#py("pop") the top item off the stack
and return it, and to
#py("initialize") the stack to empty.

#idx("makestack", decl: true)
#snippet(```python
def make_stack():
    stack = None
    def push(x):
        nonlocal stack
        stack = pair(x, stack)
        return "done"
    def pop():
        nonlocal stack
        if is_null(stack):
            error("empty stack -- pop")
        else:
            top = head(stack)
            stack = tail(stack)
            return top
    def initialize():
        nonlocal stack
        stack = None
        return "done"
    def dispatch(message):
        return (push if message == "push"
                else pop() if message == "pop"
                else initialize() if message == "initialize"
                else error("unknown request -- stack", message))
    return dispatch
```)

The following
functions
are used to access stacks:
#idx("pop", decl: true)#idx("push", decl: true)
#snippet(```python
def pop(stack):
    return stack("pop")
def push(stack, value):
    return stack("push")(value)
```)

#subheading([The basic machine])

The
#py("make_new_machine")
function,
shown in figure @fig:make-new-machine, constructs an
object whose local state consists of a stack, an initially empty instruction
sequence, a list of operations that initially contains an operation to
#idx("initializestack operation in register machine")
initialize the stack, and a
#idx("register table, in simulator")
#emph[register table] that initially contains two
registers, named
#idx("flag register")
#py("flag") and
#idx("pc register")
#py("pc")
#idx("program counter")
(for "program counter"). The internal
function
#py("allocate_register")
adds new entries to the register table, and the internal
function
#py("lookup_register")
looks up registers in the table.

#sicp-figure([#snippet(```python
def make_new_machine():
    pc = make_register("pc")
    flag = make_register("flag")
    stack = make_stack()
    the_instruction_sequence = None
    the_ops = llist(llist("initialize_stack", lambda: stack("initialize")))
    register_table = llist(llist("pc", pc), llist("flag", flag))
    def allocate_register(name):
        nonlocal register_table
        if is_undefined(assoc(name, register_table)):
            register_table = pair(llist(name, make_register(name)),
                                  register_table)
        else:
            error("multiply defined register", name)
        return "register allocated"
    def lookup_register(name):
        val = assoc(name, register_table)
        return (error("unknown register", name) if is_undefined(val)
                else head(tail(val)))
    def execute():
        insts = get_contents(pc)
        if is_null(insts):
            return "done"
        else:
            inst_execution_fun(head(insts))()
            return execute()
    def dispatch(message):
        def start():
            set_contents(pc, the_instruction_sequence)
            return execute()
        def install_instruction_sequence(seq):
            nonlocal the_instruction_sequence
            the_instruction_sequence = seq
        def install_operations(ops):
            nonlocal the_ops
            the_ops = append(the_ops, ops)
        return (start() if message == "start"
                else install_instruction_sequence
                     if message == "install_instruction_sequence"
                else allocate_register if message == "allocate_register"
                else lookup_register if message == "get_register"
                else install_operations if message == "install_operations"
                else stack if message == "stack"
                else the_ops if message == "operations"
                else error("unknown request -- machine", message))
    return dispatch
```)], caption: [The #idx("makenewmachine", decl: true) #py("make_new_machine") function implements the basic machine model.], label-name: <fig:make-new-machine>)

The #py("flag") register is used to control branching
in the simulated machine.
Our #py("test")
instructions set the contents of
#py("flag") to the result of the test (true or false).
Our #py("branch")
instructions decide whether or not to branch by examining the contents of
#py("flag").

The #py("pc") register determines the sequencing of
instructions as the machine runs. This sequencing is implemented by the
internal
function
#py("execute").
In the simulation model, each machine instruction is a data structure
that includes a
function
of no arguments, called the
#idx("instruction execution function")
#idx("execution function", sub: "in register-machine simulator")
#emph[instruction execution function],
such that calling this
function
simulates executing the instruction. As the simulation runs,
#py("pc") points to the place in the instruction
sequence beginning with the next instruction to be executed.
#idx("execute")
The function #py("execute")
gets that instruction, executes it by calling the instruction execution
function,
and repeats this cycle until there are no more instructions to execute
(i.e., until #py("pc") points to the end of the
instruction sequence).

As part of its operation, each instruction execution
function
modifies
#py("pc") to indicate the next instruction to be
executed.
The instructions #py("branch") and #py("go_to")
change #py("pc") to point to the new destination.
All other instructions simply advance #py("pc"),
making it point to the next instruction in the sequence. Observe that
each call to #py("execute") calls
#py("execute") again, but this does not produce an
infinite loop because running the instruction execution
function
changes the contents of #py("pc").

The function #py("make_new_machine")
returns a
dispatch
function
that implements message-passing access to the internal state. Notice that
starting the machine is accomplished by setting
#py("pc") to the beginning of the instruction sequence
and calling #py("execute").

For convenience, we provide an alternate

interface to a machine's
#py("start") operation, as well as
functions
to set and examine register contents, as specified at the beginning of
section @sec:simulator:
#idx("start register machine", decl: true)#idx("getregistercontents", decl: true)#idx("setregistercontents", decl: true)
#snippet(```python
def start(machine):
    return machine("start")
def get_register_contents(machine, register_name):
    return get_contents(get_register(machine, register_name))
def set_register_contents(machine, register_name, value):
    set_contents(get_register(machine, register_name), value)
    return "done"
```)

These
functions
(and many
functions
in sections @sec:assembler and @sec:ex-proc)
use the following to look up the register with a given name in a given
machine:
#idx("getregister", decl: true)
#snippet(```python
def get_register(machine, reg_name):
    return machine("get_register")(reg_name)
```)
