//! Bit-exact differential test against the original C implementation.
//!
//! `tests/fixtures/f80_reference.txt` is generated by `tools/f80-dump.c`,
//! compiled against the *unmodified* iSH `emu/float80.c` (see
//! `tools/gen_f80_reference.sh`). Every line records an operation, its inputs
//! and the C result; this test replays all of them through the Rust port and
//! requires the significand *and* the packed sign/exponent word to match
//! exactly — no tolerance, no "close enough".
//!
//! Regenerate the fixture with:
//!
//! ```text
//! ./tools/gen_f80_reference.sh /path/to/ish-checkout
//! ```

use ish_emu::float80::{self as f80, Float80, RoundingMode};

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/f80_reference.txt");

fn mode_of(m: u32) -> RoundingMode {
    match m {
        0 => RoundingMode::RoundToNearest,
        1 => RoundingMode::RoundDown,
        2 => RoundingMode::RoundUp,
        _ => RoundingMode::RoundChop,
    }
}

fn hex(s: &str) -> u64 {
    u64::from_str_radix(s, 16).unwrap_or_else(|_| panic!("bad hex {s:?}"))
}

fn hex16(s: &str) -> u16 {
    u16::from_str_radix(s, 16).unwrap_or_else(|_| panic!("bad hex16 {s:?}"))
}

fn operand(t: &[&str], i: usize) -> Float80 {
    Float80::from_bits(hex(t[i]), hex16(t[i + 1]))
}

fn show(signif: u64, sign_exp: u16) -> String {
    format!("{signif:016x} {sign_exp:04x}")
}

fn show_f(f: Float80) -> String {
    show(f.signif, f.sign_exp)
}

#[test]
fn matches_c_reference_bit_for_bit() {
    let text = std::fs::read_to_string(FIXTURE)
        .unwrap_or_else(|e| panic!("cannot read {FIXTURE}: {e}\nRun tools/gen_f80_reference.sh"));

    let mut checks: u64 = 0;
    let mut failures: u64 = 0;
    let mut samples: Vec<String> = Vec::new();

    let record = |line: &str, got: String, want: String,
                      checks: &mut u64, failures: &mut u64, samples: &mut Vec<String>| {
        *checks += 1;
        if got != want {
            *failures += 1;
            if samples.len() < 25 {
                samples.push(format!("  {line}\n      C reference: {want}\n      Rust port  : {got}"));
            }
        }
    };

    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let t: Vec<&str> = line.split_whitespace().collect();
        let (kind, op) = (t[0], t[2]);
        f80::set_rounding_mode(mode_of(t[1].parse().unwrap()));

        match kind {
            // binary float op: kind mode op a(2) b(2) result(2)
            "B" => {
                let (a, b) = (operand(&t, 3), operand(&t, 5));
                let r = match op {
                    "add" => f80::f80_add(a, b),
                    "sub" => f80::f80_sub(a, b),
                    "mul" => f80::f80_mul(a, b),
                    "div" => f80::f80_div(a, b),
                    "mod" => f80::f80_mod(a, b),
                    other => panic!("unknown binary op {other}"),
                };
                record(line, show_f(r), show(hex(t[7]), hex16(t[8])),
                       &mut checks, &mut failures, &mut samples);
            }
            // comparison: kind mode op a(2) b(2) 0|1
            "C" => {
                let (a, b) = (operand(&t, 3), operand(&t, 5));
                let r = match op {
                    "lt" => f80::f80_lt(a, b),
                    "eq" => f80::f80_eq(a, b),
                    "uncomparable" => f80::f80_uncomparable(a, b),
                    other => panic!("unknown comparison {other}"),
                };
                record(line, (r as u8).to_string(), t[7].to_string(),
                       &mut checks, &mut failures, &mut samples);
            }
            // unary float op: kind mode op a(2) result(2)
            "N" => {
                let a = operand(&t, 3);
                let r = match op {
                    "neg" => a.neg(),
                    "abs" => a.abs(),
                    "round" => a.round(),
                    "sqrt" => f80::f80_sqrt(a),
                    "log2" => f80::f80_log2(a),
                    other => panic!("unknown unary op {other}"),
                };
                record(line, show_f(r), show(hex(t[5]), hex16(t[6])),
                       &mut checks, &mut failures, &mut samples);
            }
            // predicate: kind mode pred a(2) 0|1
            "U" => {
                let a = operand(&t, 3);
                let r = match op {
                    "isnan" => a.is_nan(),
                    "isinf" => a.is_inf(),
                    "iszero" => a.is_zero(),
                    "isdenormal" => a.is_denormal(),
                    "is_supported" => a.is_supported(),
                    other => panic!("unknown predicate {other}"),
                };
                record(line, (r as u8).to_string(), t[5].to_string(),
                       &mut checks, &mut failures, &mut samples);
            }
            // xtract: kind mode xtract a(2) exp(i32 as hex) result(2)
            "X" => {
                let a = operand(&t, 3);
                let (exp, signif) = f80::f80_xtract(a);
                let want_exp = hex(t[5]) as u32 as i32;
                record(line, exp.to_string(), want_exp.to_string(),
                       &mut checks, &mut failures, &mut samples);
                record(line, show_f(signif), show(hex(t[6]), hex16(t[7])),
                       &mut checks, &mut failures, &mut samples);
            }
            // to_double: kind mode to_double a(2) f64 bits
            "E" => {
                let a = operand(&t, 3);
                record(line, format!("{:016x}", a.to_f64().to_bits()), t[5].to_string(),
                       &mut checks, &mut failures, &mut samples);
            }
            // from_int: kind mode from_int i64(hex) result(2)
            "I" => {
                let i = hex(t[3]) as i64;
                let r = Float80::from_i64(i);
                record(line, show_f(r), show(hex(t[4]), hex16(t[5])),
                       &mut checks, &mut failures, &mut samples);
            }
            // to_int: kind mode to_int a(2) i64(hex)
            "T" => {
                let a = operand(&t, 3);
                record(line, format!("{:016x}", a.to_i64() as u64), t[5].to_string(),
                       &mut checks, &mut failures, &mut samples);
            }
            // from_double: kind mode from_double f64 bits result(2)
            "D" => {
                let d = f64::from_bits(hex(t[3]));
                let r = Float80::from_f64(d);
                record(line, show_f(r), show(hex(t[4]), hex16(t[5])),
                       &mut checks, &mut failures, &mut samples);
            }
            // scale: kind mode scale a(2) scale(i32 dec) result(2)
            "S" => {
                let a = operand(&t, 3);
                let scale: i32 = t[5].parse().unwrap();
                let r = f80::f80_scale(a, scale);
                record(line, show_f(r), show(hex(t[6]), hex16(t[7])),
                       &mut checks, &mut failures, &mut samples);
            }
            other => panic!("unknown record kind {other} in line: {line}"),
        }
    }

    f80::set_rounding_mode(RoundingMode::RoundToNearest);

    assert!(
        failures == 0,
        "{failures} of {checks} results differ from the C reference; first {}:\n{}",
        samples.len(),
        samples.join("\n")
    );
    assert!(checks > 100_000, "only {checks} checks ran - fixture looks truncated");
    eprintln!("differential: {checks} results matched the C reference exactly");
}

/// The corner cases where the C original is itself awkward. These are pinned
/// here so a future "cleanup" of the port cannot silently drift away from the
/// behaviour that iSH actually has.
#[test]
fn upstream_corner_cases_are_reproduced() {
    // 1. smallest_normal - smallest_denormal.
    //
    // iSH's debug build trips `assert(f80_is_supported(f))` at the end of
    // f80_add on this input: the exponent underflows into the denormal range
    // *before* rounding, but rounding puts the integer bit back, so the result
    // is an encoding iSH calls unsupported. The arithmetic result itself is
    // well defined, and the Rust port produces the identical bits without
    // panicking.
    let smallest_normal = Float80::from_bits(0x8000_0000_0000_0000, 0x0001); // 2^-16382
    let smallest_denormal = Float80::from_bits(1, 0x0000); // 2^-16445
    let r = f80::f80_sub(smallest_normal, smallest_denormal);
    assert_eq!(r.to_bits(), (0x8000_0000_0000_0000, 0x0000));
    assert!(!r.is_supported(), "iSH asserts on this encoding; the port must not panic");

    // 2. f80_scale of zero by a large amount.
    //
    // C does `signif <<= 128` on a zero significand; gcc/x86 masks the shift
    // count so nothing happens, and the exponent is left at exp - 128. The
    // port uses wrapping_shl to get the same answer.
    let zero = Float80::from_bits(0, 0x0000);
    assert_eq!(f80::f80_scale(zero, 127).to_bits(), (0, 0x0000));
    assert_eq!(f80::f80_scale(zero, 128).to_bits(), (0, 0x0000));
    assert_eq!(f80::f80_scale(zero, 129).to_bits(), (0, 0x0001));
    assert_eq!(f80::f80_scale(zero, 1000).to_bits(), (0, 0x0368));

    // 3. +0.0 == -0.0 even though their encodings differ.
    assert!(f80::f80_eq(Float80::from_f64(0.0), Float80::from_f64(-0.0)));
}
