//! Differential test of `errno.rs` against the C original.
//!
//! `tests/fixtures/errno_reference.txt` is produced by `tools/errno-dump.c`,
//! which links the **unmodified** `kernel/errno.c` and prints `err_map(e)` for
//! every input from -16 to 4199 — the mapped errnos, the gaps between them, and
//! well past them so the `-(err | 0x1000)` fallback is exercised far more than
//! the table is.
//!
//! The fixture also records the host's own errno numbers, so a table generated on
//! one platform and tested on another fails loudly instead of quietly.
//!
//! Regenerate with:
//!
//! ```text
//! ISH_SRC=/path/to/ish ./tools/gen_errno_reference.sh
//! ISH_SRC=/path/to/ish ./tools/gen_errno_table.py
//! ```

use ish_emu::errno::{err_map, errno_map, is_unknown, Mapped, HOST_EPIPE};

const FIXTURE: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/errno_reference.txt");

enum Line {
    Map { input: i32, want: i32 },
    ErrnoMap { input: i32, want: i32, sigpipe: bool },
    Host { name: String, value: i32 },
    Counters { unknown: i32, sigpipes: i32 },
    Comment,
}

fn parse() -> Vec<Line> {
    let text = std::fs::read_to_string(FIXTURE)
        .unwrap_or_else(|e| panic!("cannot read {FIXTURE}: {e}"));
    let mut out = Vec::new();
    for line in text.lines() {
        let f: Vec<&str> = line.split(' ').collect();
        match f[0] {
            "M" => out.push(Line::Map {
                input: f[1].parse().unwrap(),
                want: f[2].parse().unwrap(),
            }),
            "N" => out.push(Line::ErrnoMap {
                input: f[1].parse().unwrap(),
                want: f[2].parse().unwrap(),
                sigpipe: f[3] == "1",
            }),
            "#" if f[1] == "host" && f[2] == "EPERM" => {
                // "# host EPERM 1 ENOENT 2 EAGAIN 11 EPIPE 32 EOPNOTSUPP 95 EDQUOT 122"
                let mut i = 2;
                while i + 1 < f.len() {
                    out.push(Line::Host {
                        name: f[i].to_string(),
                        value: f[i + 1].parse().unwrap(),
                    });
                    i += 2;
                }
            }
            "#" if f[1] == "unknown_errors" => out.push(Line::Counters {
                unknown: f[2].parse().unwrap(),
                sigpipes: f[4].parse().unwrap(),
            }),
            "#" => out.push(Line::Comment),
            _ => panic!("unparsed fixture line: {line}"),
        }
    }
    out
}

#[test]
fn err_map_matches_the_c_for_every_input_in_range() {
    let lines = parse();
    let mut checked = 0usize;
    let mut fallbacks = 0usize;
    let mut unknown = 0i32;
    let mut sigpipes = 0i32;
    let mut host: Vec<(String, i32)> = Vec::new();

    for line in &lines {
        match line {
            Line::Map { input, want } => {
                assert_eq!(err_map(*input), *want, "err_map({input})");
                if is_unknown(*input) {
                    unknown += 1;
                    fallbacks += 1;
                }
                checked += 1;
            }
            Line::ErrnoMap { input, want, sigpipe } => {
                assert_eq!(
                    errno_map(*input),
                    Mapped { guest: *want, sigpipe: *sigpipe },
                    "errno_map({input})"
                );
                if *sigpipe {
                    sigpipes += 1;
                }
                // errno_map() runs err_map() too, so its unknown inputs reach the
                // C's printk as well - two of the ten probes are unknown
                if is_unknown(*input) {
                    unknown += 1;
                }
            }
            Line::Host { name, value } => host.push((name.clone(), *value)),
            Line::Counters { unknown: want_unknown, sigpipes: want_sigpipes } => {
                // the C printk's once per unmapped input, so its count is a
                // direct check on which inputs the port treats as unknown
                assert_eq!(unknown, *want_unknown, "printk'd unknown errors");
                assert_eq!(sigpipes, *want_sigpipes, "SIGPIPEs raised");
            }
            Line::Comment => {}
        }
    }

    assert!(checked >= 4000, "only {checked} inputs checked");
    assert!(fallbacks > 4000, "the fallback path should dominate the range");
    println!("{checked} err_map inputs matched the C exactly");

    // The fixture carries the host's own numbers. The table in src/errno_table.rs
    // was generated by asking a host for exactly these, so if the two disagree
    // the table is stale for this platform - and every comparison above would be
    // comparing against the wrong half of the mapping.
    let expect: std::collections::HashMap<&str, i32> =
        host.iter().map(|(n, v)| (n.as_str(), *v)).collect();
    assert_eq!(expect["EPIPE"], HOST_EPIPE, "the table's EPIPE is not this host's");
    assert_eq!(err_map(expect["EPERM"]), -1);
    assert_eq!(err_map(expect["ENOENT"]), -2);
    assert_eq!(err_map(expect["EAGAIN"]), -11);
    assert_eq!(err_map(expect["EOPNOTSUPP"]), -95);
    assert_eq!(err_map(expect["EDQUOT"]), -122);
    assert!(!is_unknown(expect["EPERM"]));
}

#[test]
fn the_fallback_is_an_or_not_an_add() {
    // -(err | 0x1000) and -(err + 0x1000) agree everywhere except where bit 12
    // is already set, and the corpus covers both sides of that
    for e in 0..4200i32 {
        let or = -(e | 0x1000);
        let add = -(e + 0x1000);
        if e & 0x1000 != 0 {
            assert_ne!(or, add, "e={e:x} should distinguish the two");
            if is_unknown(e) {
                assert_eq!(err_map(e), or, "err_map({e}) uses the or form");
            }
        }
    }
}

#[test]
fn a_negative_input_can_come_back_positive() {
    // the fallback negates, and for a negative input whose bit 12 is already set
    // that means a positive result - which is what the C does too
    assert_eq!(err_map(-16), 16);
    assert_eq!(err_map(-4096), 4096);
}
