//! Differential test of `resource.rs` against the unmodified C implementation.
//!
//! `tests/fixtures/resource_reference.txt` is generated by
//! `tools/resource-dump.c`, which links the original `kernel/resource.c` with a
//! deterministic task/group and two-page guest-memory harness. Its two host
//! dependencies are wrapped at link time: each corpus record supplies the
//! current-thread rusage values and online CPU count, so this comparison never
//! depends on the machine running it.
//!
//! Regenerate locally with:
//!
//! ```text
//! ISH_SRC=/path/to/ish ./tools/gen_resource_reference.sh
//! ```
//!
//! The fixture deliberately clears the undefined tail of C's
//! `rusage_get_current` result after testing its defined timeval prefix. Every
//! other output byte, all 16 limits, all child-rusage words, the superuser
//! identity, and a hash of the full guest-memory window are compared after each
//! C operation.

use ish_emu::memory::P_RWX;
use ish_emu::mmu::PAGE_BITS;
use ish_emu::resource::{self, Rlimit, Rusage, StaticResourceHost, Timeval, RLIMIT_NLIMITS};
use ish_emu::task::{Addr, TaskTable};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/resource_reference.txt"
);
const GUEST_BASE: Addr = 0x001000;
const GUEST_SIZE: usize = 0x002000;
const GROUP_LEADER: i32 = 1;

#[derive(Debug)]
enum ReturnValue {
    Raw(i32),
    Limit(u64),
}

#[derive(Debug)]
struct Pending {
    description: String,
    result: ReturnValue,
    current_rusage: Option<Rusage>,
    saw_return: bool,
}

fn hex32(text: &str) -> u32 {
    u32::from_str_radix(text, 16).unwrap_or_else(|err| panic!("invalid u32 `{text}`: {err}"))
}

fn hex64(text: &str) -> u64 {
    u64::from_str_radix(text, 16).unwrap_or_else(|err| panic!("invalid u64 `{text}`: {err}"))
}

fn signed(text: &str) -> i32 {
    hex32(text) as i32
}

fn decode_bytes(text: &str) -> Vec<u8> {
    assert_eq!(text.len() % 2, 0, "odd-length byte record `{text}`");
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).unwrap())
        .collect()
}

fn rusage_from_fields(fields: &[&str]) -> Rusage {
    assert_eq!(fields.len(), 18, "rusage must have 18 i386 words");
    let words: Vec<u32> = fields.iter().map(|field| hex32(field)).collect();
    Rusage {
        utime: Timeval {
            sec: words[0],
            usec: words[1],
        },
        stime: Timeval {
            sec: words[2],
            usec: words[3],
        },
        maxrss: words[4],
        ixrss: words[5],
        idrss: words[6],
        isrss: words[7],
        minflt: words[8],
        majflt: words[9],
        nswap: words[10],
        inblock: words[11],
        oublock: words[12],
        msgsnd: words[13],
        msgrcv: words[14],
        nsignals: words[15],
        nvcsw: words[16],
        nivcsw: words[17],
    }
}

fn new_table() -> TaskTable {
    let mut table = TaskTable::bootstrap();
    {
        let task = table.current().expect("bootstrap task");
        let mut mm = task.mm_mut().expect("bootstrap mm");
        assert_eq!(
            mm.mem.map_nothing(GUEST_BASE >> PAGE_BITS, 2, P_RWX),
            0,
            "map the same two-page guest window as resource-dump.c"
        );
    }
    let seed: Vec<u8> = (0..GUEST_SIZE)
        .map(|index| (index as u32).wrapping_mul(37).wrapping_add(23) as u8)
        .collect();
    table
        .current_mut()
        .expect("bootstrap current")
        .user_write(GUEST_BASE, &seed)
        .expect("seed guest window");
    table
}

fn guest_hash(table: &mut TaskTable) -> u64 {
    let mut bytes = vec![0; GUEST_SIZE];
    table
        .current_mut()
        .expect("current task")
        .user_read(GUEST_BASE, &mut bytes)
        .expect("the fixture's two guest pages stay mapped");
    bytes
        .into_iter()
        .fold(0xcbf2_9ce4_8422_2325u64, |hash, byte| {
            (hash ^ u64::from(byte)).wrapping_mul(0x0000_0100_0000_01b3)
        })
}

fn apply_prep(fields: &[&str], table: &mut TaskTable, host: &mut StaticResourceHost) {
    assert!(fields.len() >= 3, "short preparation record: {fields:?}");
    match fields[1] {
        "UID" => {
            assert_eq!(fields.len(), 3);
            table.current_mut().expect("current task").credentials.euid = hex32(fields[2]);
        }
        "LIM" => {
            assert_eq!(fields.len(), 5);
            let resource = hex32(fields[2]) as usize;
            assert!(resource < RLIMIT_NLIMITS, "invalid prepared resource");
            table
                .thread_group_mut(GROUP_LEADER)
                .expect("bootstrap group")
                .limits[resource] = Rlimit::new(hex64(fields[3]), hex64(fields[4]));
        }
        "CHILD" => {
            assert_eq!(fields.len(), 20);
            table
                .thread_group_mut(GROUP_LEADER)
                .expect("bootstrap group")
                .children_rusage = rusage_from_fields(&fields[2..]);
        }
        "HOST" => {
            assert_eq!(fields.len(), 6);
            host.rusage = Rusage {
                utime: Timeval {
                    sec: hex32(fields[2]),
                    usec: hex32(fields[3]),
                },
                stime: Timeval {
                    sec: hex32(fields[4]),
                    usec: hex32(fields[5]),
                },
                // resource.c leaves these fields unspecified for the host
                // result. The C fixture only compares the defined prefix.
                ..Rusage::default()
            };
        }
        "CPUS" => {
            assert_eq!(fields.len(), 3);
            host.cpus = hex32(fields[2]) as usize;
        }
        other => panic!("unknown preparation kind `{other}`"),
    }
}

fn run_op(fields: &[&str], table: &mut TaskTable, host: &StaticResourceHost) -> Pending {
    assert!(fields.len() >= 2, "short operation record: {fields:?}");
    let description = fields[1..].join(" ");
    let raw = match fields[1] {
        "RL" => {
            assert_eq!(fields.len(), 3);
            return Pending {
                description,
                result: ReturnValue::Limit(resource::rlimit(table, hex32(fields[2])).unwrap()),
                current_rusage: None,
                saw_return: false,
            };
        }
        "G32" => {
            assert_eq!(fields.len(), 4);
            resource::sys_getrlimit32(table, hex32(fields[2]), hex32(fields[3]))
        }
        "OG32" => {
            assert_eq!(fields.len(), 4);
            resource::sys_old_getrlimit32(table, hex32(fields[2]), hex32(fields[3]))
        }
        "S32" => {
            assert_eq!(fields.len(), 4);
            resource::sys_setrlimit32(table, hex32(fields[2]), hex32(fields[3]))
        }
        "PR" => {
            assert_eq!(fields.len(), 6);
            resource::sys_prlimit64(
                table,
                signed(fields[2]),
                hex32(fields[3]),
                hex32(fields[4]),
                hex32(fields[5]),
            )
        }
        "RC" => {
            assert_eq!(fields.len(), 2);
            return Pending {
                description,
                result: ReturnValue::Raw(0),
                current_rusage: Some(resource::rusage_get_current(host)),
                saw_return: false,
            };
        }
        "RU" => {
            assert_eq!(fields.len(), 4);
            resource::sys_getrusage(table, host, hex32(fields[2]), hex32(fields[3]))
        }
        "ADD" => {
            assert_eq!(fields.len(), 20);
            let src = rusage_from_fields(&fields[2..]);
            let group = table
                .thread_group_mut(GROUP_LEADER)
                .expect("bootstrap group");
            resource::rusage_add(&mut group.children_rusage, src);
            0
        }
        "AFF" => {
            assert_eq!(fields.len(), 5);
            resource::sys_sched_getaffinity(
                table,
                host,
                signed(fields[2]),
                hex32(fields[3]),
                hex32(fields[4]),
            )
        }
        "SAFF" => {
            assert_eq!(fields.len(), 5);
            resource::sys_sched_setaffinity(signed(fields[2]), hex32(fields[3]), hex32(fields[4]))
        }
        "GPRI" => {
            assert_eq!(fields.len(), 4);
            resource::sys_getpriority(signed(fields[2]), signed(fields[3]))
        }
        "SPRI" => {
            assert_eq!(fields.len(), 5);
            resource::sys_setpriority(signed(fields[2]), signed(fields[3]), signed(fields[4]))
        }
        "GPAR" => {
            assert_eq!(fields.len(), 4);
            resource::sys_sched_getparam(table, signed(fields[2]), hex32(fields[3]))
        }
        "GSCH" => {
            assert_eq!(fields.len(), 3);
            resource::sys_sched_getscheduler(signed(fields[2]))
        }
        "SSCH" => {
            assert_eq!(fields.len(), 5);
            resource::sys_sched_setscheduler(
                table,
                signed(fields[2]),
                signed(fields[3]),
                hex32(fields[4]),
            )
        }
        "PMAX" => {
            assert_eq!(fields.len(), 3);
            resource::sys_sched_get_priority_max(signed(fields[2]))
        }
        "IGET" => {
            assert_eq!(fields.len(), 5);
            // iSH's C syscall ABI takes an unused third register argument;
            // the Rust surface intentionally exposes the two semantic inputs.
            resource::sys_ioprio_get(signed(fields[2]), signed(fields[3]))
        }
        "ISET" => {
            assert_eq!(fields.len(), 5);
            resource::sys_ioprio_set(signed(fields[2]), signed(fields[3]), signed(fields[4]))
        }
        other => panic!("unknown resource operation `{other}`"),
    };
    Pending {
        description,
        result: ReturnValue::Raw(raw),
        current_rusage: None,
        saw_return: false,
    }
}

fn check_snapshot(fields: &[&str], table: &mut TaskTable, context: &str) {
    // S, euid, 16 x (cur,max), 18 rusage words, FNV-1a hash.
    assert_eq!(fields.len(), 53, "{context}: malformed state record");
    let expected_euid = hex32(fields[1]);
    let mut index = 2;
    let mut expected_limits = Vec::with_capacity(RLIMIT_NLIMITS);
    for _ in 0..RLIMIT_NLIMITS {
        expected_limits.push(Rlimit::new(hex64(fields[index]), hex64(fields[index + 1])));
        index += 2;
    }
    let expected_children = rusage_from_fields(&fields[index..index + 18]);
    index += 18;
    let expected_hash = hex64(fields[index]);
    assert_eq!(index + 1, fields.len());

    let got_euid = table.current().expect("current task").credentials.euid;
    let (got_limits, got_children) = {
        let group = table.thread_group(GROUP_LEADER).expect("bootstrap group");
        (group.limits, group.children_rusage)
    };
    assert_eq!(got_euid, expected_euid, "{context}: effective UID");
    for (resource, (got, expected)) in got_limits.iter().zip(expected_limits.iter()).enumerate() {
        assert_eq!(got, expected, "{context}: rlimit[{resource}]");
    }
    assert_eq!(
        got_children, expected_children,
        "{context}: children rusage (all 18 ABI words)"
    );
    assert_eq!(
        guest_hash(table),
        expected_hash,
        "{context}: guest memory FNV-1a"
    );
}

#[test]
fn resource_matches_the_c_reference() {
    let fixture = std::fs::read_to_string(FIXTURE)
        .unwrap_or_else(|err| panic!("cannot read {FIXTURE}: {err}"));
    let mut table = new_table();
    let mut host = StaticResourceHost::default();
    let mut pending: Option<Pending> = None;
    let mut ops = 0usize;
    let mut snapshots = 0usize;

    for line in fixture.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split(' ').collect();
        match fields[0] {
            "P" => {
                assert!(
                    pending.is_none(),
                    "preparation while an op is pending: {line}"
                );
                apply_prep(&fields, &mut table, &mut host);
            }
            "W" => {
                assert_eq!(fields.len(), 3, "malformed guest write: {line}");
                assert!(
                    pending.is_none(),
                    "guest write while an op is pending: {line}"
                );
                let bytes = decode_bytes(fields[2]);
                table
                    .current_mut()
                    .expect("current task")
                    .user_write(hex32(fields[1]), &bytes)
                    .unwrap_or_else(|_| panic!("fixture guest write faulted: {line}"));
            }
            "O" => {
                assert!(
                    pending.is_none(),
                    "operation before previous snapshot: {line}"
                );
                pending = Some(run_op(&fields, &mut table, &host));
            }
            "R" => {
                assert_eq!(fields.len(), 2, "malformed return: {line}");
                let operation = pending.as_mut().expect("return without an operation");
                assert!(
                    !operation.saw_return,
                    "duplicate return for {}",
                    operation.description
                );
                let want = hex64(fields[1]);
                match operation.result {
                    ReturnValue::Raw(got) => assert_eq!(
                        got as u32 as u64, want,
                        "{}: raw i386 return",
                        operation.description
                    ),
                    ReturnValue::Limit(got) => {
                        assert_eq!(got, want, "{}: rlimit helper", operation.description)
                    }
                }
                operation.saw_return = true;
            }
            "V" => {
                assert_eq!(fields.len(), 6, "malformed value record: {line}");
                assert_eq!(fields[1], "CURRENT", "unknown value record: {line}");
                let operation = pending.as_mut().expect("value without an operation");
                assert!(
                    operation.saw_return,
                    "value appeared before return for {}",
                    operation.description
                );
                let got = operation
                    .current_rusage
                    .take()
                    .expect("CURRENT value for a non-current-rusage operation");
                assert_eq!(
                    [got.utime.sec, got.utime.usec, got.stime.sec, got.stime.usec],
                    [
                        hex32(fields[2]),
                        hex32(fields[3]),
                        hex32(fields[4]),
                        hex32(fields[5]),
                    ],
                    "{}: defined rusage timeval prefix",
                    operation.description
                );
            }
            "S" => {
                let context = match pending.as_ref() {
                    Some(operation) => operation.description.clone(),
                    None => "initial deterministic resource state".to_owned(),
                };
                if let Some(operation) = pending.as_ref() {
                    assert!(
                        operation.saw_return,
                        "missing return for {}",
                        operation.description
                    );
                    assert!(
                        operation.current_rusage.is_none(),
                        "missing CURRENT value for {}",
                        operation.description
                    );
                    ops += 1;
                } else {
                    assert_eq!(snapshots, 0, "unexpected standalone state snapshot");
                }
                check_snapshot(&fields, &mut table, &context);
                pending = None;
                snapshots += 1;
            }
            other => panic!("unknown resource fixture record `{other}`: {line}"),
        }
    }

    assert!(pending.is_none(), "fixture ended with a pending operation");
    assert_eq!(
        snapshots,
        ops + 1,
        "one initial snapshot plus one per operation"
    );
    assert_eq!(ops, 51, "the C generator's complete deterministic corpus");
    println!("{ops} resource operations and {snapshots} full C-state snapshots matched exactly");
}
