//! Word-for-word differential test of `vec.rs` against the C original.
//!
//! `tests/fixtures/vec_reference.txt` is produced by `tools/vec-dump.c`,
//! compiled against the **unmodified** iSH `emu/vec.c` and `emu/mmx.c`. It
//! calls every one of the 166 functions `emu/vec.h` declares — the op table is
//! generated from that header by `tools/gen_vec_ops.py`, so nothing can be
//! quietly left out — over 50 operand cases chosen to hit the corners:
//! saturating arithmetic, signed and unsigned compares, shift counts just past
//! every element width, shuffle encodings, insert/extract indices, all eight
//! float-compare predicates, and NaN/±inf/denormal/overflow operands for the
//! conversions.
//!
//! After each call the C dumps the destination register, the source register,
//! a side buffer for the operations whose destination is a bare scalar, and
//! nine `cpu_state` flag fields. That last part is what proves only the two
//! `ucomi` operations touch the CPU at all.
//!
//! The dispatch match below is generated by the same script
//! (`tools/gen_vec_ops.py <ish> --rust`); an operation present in the fixture
//! but missing here panics on its name rather than passing silently.
//!
//! Regenerate with:
//!
//! ```text
//! ISH_SRC=/path/to/ish ./tools/gen_vec_reference.sh
//! ```

use std::collections::BTreeSet;

use ish_emu::cpu::{CpuState, MmReg, XmmReg};
use ish_emu::vec;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/vec_reference.txt");

/// One operand case. The values come out of the fixture header, so the Rust
/// side never has to duplicate the C driver's tables.
#[derive(Clone, Copy, Debug)]
struct Case {
    src: [u8; 16],
    dst: [u8; 16],
    encoding: u8,
    index: u8,
    amount: u8,
    type_: u8,
}

fn hex16(fields: &[&str]) -> [u8; 16] {
    let mut out = [0u8; 16];
    for (i, f) in fields.iter().enumerate() {
        out[i] = u8::from_str_radix(f, 16).unwrap();
    }
    out
}

fn parse_fixture() -> (Vec<Case>, Vec<Vec<String>>) {
    let text = std::fs::read_to_string(FIXTURE)
        .unwrap_or_else(|e| panic!("cannot read {FIXTURE}: {e}"));
    let mut cases = Vec::new();
    let mut records = Vec::new();
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("# C ") {
            let f: Vec<&str> = rest.split(' ').collect();
            assert_eq!(f.len(), 1 + 32 + 4, "malformed case line");
            cases.push(Case {
                src: hex16(&f[1..17]),
                dst: hex16(&f[17..33]),
                encoding: u8::from_str_radix(f[33], 16).unwrap(),
                index: u8::from_str_radix(f[34], 16).unwrap(),
                amount: u8::from_str_radix(f[35], 16).unwrap(),
                type_: u8::from_str_radix(f[36], 16).unwrap(),
            });
        } else if line.starts_with("V ") {
            records.push(line.split(' ').map(|s| s.to_string()).collect());
        }
    }
    (cases, records)
}

#[test]
fn vec_matches_the_c_reference() {
    let (cases, records) = parse_fixture();
    assert!(!cases.is_empty(), "the fixture has no case table");
    assert!(!records.is_empty(), "the fixture has no records");

    let mut seen = BTreeSet::new();
    let mut compared = 0usize;
    for r in &records {
        let f: Vec<&str> = r.iter().map(|s| s.as_str()).collect();
        let name = f[1];
        let idx: usize = f[2].parse().unwrap();
        assert_eq!(f.len(), 3 + 48 + 9, "{name}: wrong field count");
        let want_dst = hex16(&f[3..19]);
        let want_src = hex16(&f[19..35]);
        let want_out = hex16(&f[35..51]);
        let want_flags: Vec<u8> = f[51..60].iter().map(|s| s.parse().unwrap()).collect();
        seen.insert(name);

        let c = &cases[idx];
        let mut src = XmmReg::from_bytes(c.src);
        let mut dst = XmmReg::from_bytes(c.dst);
        let mut out = [0u8; 16];
        let mut cpu = CpuState::default();
        let ctx = || format!("{name} case {idx}");

        // the input the C actually used, as recorded in its own dump
        assert_eq!(src.bytes(), want_src, "{}: inputs disagree with the C", ctx());

        match name {
        // Generated by tools/gen_vec_ops.py from emu/vec.h - do not edit.
        "vec_zero128_copy128" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_zero128_copy128(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_zero128_copy64" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_zero128_copy64(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_zero128_copy32" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_zero128_copy32(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_zero64_copy64" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_zero64_copy64(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_zero64_copy32" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_zero64_copy32(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_zero32_copy32" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_zero32_copy32(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_merge32" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_merge32(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_merge64" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_merge64(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_merge128" => { let sb = src.bytes(); let mut db = dst.bytes(); vec::vec_merge128(&sb, &mut db); dst = XmmReg::from_bytes(db); },
        "vec_shiftl_w64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftl_w64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftl_d64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftl_d64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftl_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftl_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftr_w64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftr_w64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftr_d64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftr_d64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftr_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftr_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftrs_w64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftrs_w64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftrs_d64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shiftrs_d64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_shiftl_w128" => vec::vec_shiftl_w128(&src, &mut dst),
        "vec_shiftl_d128" => vec::vec_shiftl_d128(&src, &mut dst),
        "vec_shiftl_q128" => vec::vec_shiftl_q128(&src, &mut dst),
        "vec_shiftr_w128" => vec::vec_shiftr_w128(&src, &mut dst),
        "vec_shiftr_d128" => vec::vec_shiftr_d128(&src, &mut dst),
        "vec_shiftr_q128" => vec::vec_shiftr_q128(&src, &mut dst),
        "vec_shiftrs_w128" => vec::vec_shiftrs_w128(&src, &mut dst),
        "vec_shiftrs_d128" => vec::vec_shiftrs_d128(&src, &mut dst),
        "vec_imm_shiftl_w64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftl_w64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftl_d64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftl_d64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftl_q64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftl_q64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftr_w64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftr_w64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftr_d64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftr_d64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftr_q64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftr_q64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftrs_w64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftrs_w64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftrs_d64" => { let mut dm = MmReg(dst.qw(0)); vec::vec_imm_shiftrs_d64(c.amount, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_imm_shiftl_w128" => vec::vec_imm_shiftl_w128(c.amount, &mut dst),
        "vec_imm_shiftl_q128" => vec::vec_imm_shiftl_q128(c.amount, &mut dst),
        "vec_imm_shiftl_d128" => vec::vec_imm_shiftl_d128(c.amount, &mut dst),
        "vec_imm_shiftl_dq128" => vec::vec_imm_shiftl_dq128(c.amount, &mut dst),
        "vec_imm_shiftr_q128" => vec::vec_imm_shiftr_q128(c.amount, &mut dst),
        "vec_imm_shiftr_w128" => vec::vec_imm_shiftr_w128(c.amount, &mut dst),
        "vec_imm_shiftr_d128" => vec::vec_imm_shiftr_d128(c.amount, &mut dst),
        "vec_imm_shiftr_dq128" => vec::vec_imm_shiftr_dq128(c.amount, &mut dst),
        "vec_imm_shiftrs_w128" => vec::vec_imm_shiftrs_w128(c.amount, &mut dst),
        "vec_imm_shiftrs_d128" => vec::vec_imm_shiftrs_d128(c.amount, &mut dst),
        "vec_add_b64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_add_b64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_add_w64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_add_w64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_add_d64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_add_d64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_add_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_add_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_sub_b64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_sub_b64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_sub_w64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_sub_w64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_sub_d64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_sub_d64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_sub_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_sub_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_add_b128" => vec::vec_add_b128(&src, &mut dst),
        "vec_add_w128" => vec::vec_add_w128(&src, &mut dst),
        "vec_add_d128" => vec::vec_add_d128(&src, &mut dst),
        "vec_add_q128" => vec::vec_add_q128(&src, &mut dst),
        "vec_addus_b128" => vec::vec_addus_b128(&mut src, &mut dst),
        "vec_addus_w128" => vec::vec_addus_w128(&mut src, &mut dst),
        "vec_addss_b128" => vec::vec_addss_b128(&mut src, &mut dst),
        "vec_addss_w128" => vec::vec_addss_w128(&mut src, &mut dst),
        "vec_sub_b128" => vec::vec_sub_b128(&src, &mut dst),
        "vec_sub_w128" => vec::vec_sub_w128(&src, &mut dst),
        "vec_sub_d128" => vec::vec_sub_d128(&src, &mut dst),
        "vec_sub_q128" => vec::vec_sub_q128(&src, &mut dst),
        "vec_subus_b128" => vec::vec_subus_b128(&mut src, &mut dst),
        "vec_subus_w128" => vec::vec_subus_w128(&mut src, &mut dst),
        "vec_subss_b128" => vec::vec_subss_b128(&mut src, &mut dst),
        "vec_subss_w128" => vec::vec_subss_w128(&mut src, &mut dst),
        "vec_mulu_dq128" => vec::vec_mulu_dq128(&mut src, &mut dst),
        "vec_mulu_dq64" => { let mut sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_mulu_dq64(&mut sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_mulu64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_mulu64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_mull64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_mull64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_mulu128" => vec::vec_mulu128(&src, &mut dst),
        "vec_muluu128" => vec::vec_muluu128(&src, &mut dst),
        "vec_mull128" => vec::vec_mull128(&src, &mut dst),
        "vec_madd_d128" => vec::vec_madd_d128(&mut src, &mut dst),
        "vec_sumabs_w128" => vec::vec_sumabs_w128(&mut src, &mut dst),
        "vec_add_p64" => vec::vec_add_p64(&mut src, &mut dst),
        "vec_add_p32" => vec::vec_add_p32(&mut src, &mut dst),
        "vec_sub_p64" => vec::vec_sub_p64(&mut src, &mut dst),
        "vec_sub_p32" => vec::vec_sub_p32(&mut src, &mut dst),
        "vec_mul_p64" => vec::vec_mul_p64(&mut src, &mut dst),
        "vec_mul_p32" => vec::vec_mul_p32(&mut src, &mut dst),
        "vec_or_dq128" => vec::vec_or_dq128(&src, &mut dst),
        "vec_xor_dq128" => vec::vec_xor_dq128(&src, &mut dst),
        "vec_and_dq128" => vec::vec_and_dq128(&src, &mut dst),
        "vec_andn128" => vec::vec_andn128(&mut src, &mut dst),
        "vec_or_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_or_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_and_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_and_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_xor_q64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_xor_q64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_min_ub128" => vec::vec_min_ub128(&mut src, &mut dst),
        "vec_mins_w128" => vec::vec_mins_w128(&mut src, &mut dst),
        "vec_max_ub128" => vec::vec_max_ub128(&mut src, &mut dst),
        "vec_maxs_w128" => vec::vec_maxs_w128(&mut src, &mut dst),
        "vec_single_fadd64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fadd64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fadd32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fadd32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_fmul64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fmul64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fmul32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fmul32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_fsub64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fsub64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fsub32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fsub32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_fdiv64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fdiv64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fdiv32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fdiv32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_fsqrt64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fsqrt64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fsqrt32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fsqrt32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_fmax64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fmax64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fmax32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fmax32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_fmin64" => { let s = src.f64(0); let mut d = dst.f64(0); vec::vec_single_fmin64(&s, &mut d); dst.set_f64(0, d); },
        "vec_single_fmin32" => { let s = src.f32(0); let mut d = dst.f32(0); vec::vec_single_fmin32(&s, &mut d); dst.set_f32(0, d); },
        "vec_single_ucomi32" => { let s = src.f32(0); let d = dst.f32(0); vec::vec_single_ucomi32(&mut cpu, &s, &d); },
        "vec_single_ucomi64" => { let s = src.f64(0); let d = dst.f64(0); vec::vec_single_ucomi64(&mut cpu, &s, &d); },
        "vec_single_fcmp64" => { let s = src.f64(0); vec::vec_single_fcmp64(&s, &mut dst, c.type_); },
        "vec_single_fcmp32" => { let s = src.f32(0); vec::vec_single_fcmp32(&s, &mut dst, c.type_); },
        "vec_fcmp_p64" => vec::vec_fcmp_p64(&src, &mut dst, c.type_),
        "vec_cvtsi2sd32" => { let s = src.u32(0) as i32; let mut d = dst.f64(0); vec::vec_cvtsi2sd32(&s, &mut d); dst.set_f64(0, d); },
        "vec_cvttsd2si64" => { let s = src.f64(0); let mut d = dst.u32(0) as i32; vec::vec_cvttsd2si64(&s, &mut d); dst.set_u32(0, d as u32); },
        "vec_cvtsd2ss64" => { let s = src.f64(0); let mut d = dst.f32(0); vec::vec_cvtsd2ss64(&s, &mut d); dst.set_f32(0, d); },
        "vec_cvtsi2ss32" => { let s = src.u32(0) as i32; let mut d = dst.f32(0); vec::vec_cvtsi2ss32(&s, &mut d); dst.set_f32(0, d); },
        "vec_cvttss2si32" => { let s = src.f32(0); let mut d = dst.u32(0) as i32; vec::vec_cvttss2si32(&s, &mut d); dst.set_u32(0, d as u32); },
        "vec_cvtss2sd32" => { let s = src.f32(0); let mut d = dst.f64(0); vec::vec_cvtss2sd32(&s, &mut d); dst.set_f64(0, d); },
        "vec_cvttpd2dq64" => vec::vec_cvttpd2dq64(&src, &mut dst),
        "vec_cvttps2dq32" => vec::vec_cvttps2dq32(&src, &mut dst),
        "vec_packss_w128" => vec::vec_packss_w128(&src, &mut dst),
        "vec_packsu_w128" => vec::vec_packsu_w128(&src, &mut dst),
        "vec_packss_d128" => vec::vec_packss_d128(&src, &mut dst),
        "vec_unpackl_bw128" => vec::vec_unpackl_bw128(&src, &mut dst),
        "vec_unpackl_w128" => vec::vec_unpackl_w128(&src, &mut dst),
        "vec_unpackl_dq128" => vec::vec_unpackl_dq128(&src, &mut dst),
        "vec_unpackl_dq64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_unpackl_dq64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_unpackl_qdq128" => vec::vec_unpackl_qdq128(&src, &mut dst),
        "vec_unpackl_ps128" => vec::vec_unpackl_ps128(&src, &mut dst),
        "vec_unpackl_pd128" => vec::vec_unpackl_pd128(&src, &mut dst),
        "vec_unpackh_bw128" => vec::vec_unpackh_bw128(&src, &mut dst),
        "vec_unpackh_w128" => vec::vec_unpackh_w128(&src, &mut dst),
        "vec_unpackh_d128" => vec::vec_unpackh_d128(&src, &mut dst),
        "vec_unpackh_dq128" => vec::vec_unpackh_dq128(&src, &mut dst),
        "vec_unpackh_ps128" => vec::vec_unpackh_ps128(&src, &mut dst),
        "vec_unpackh_pd128" => vec::vec_unpackh_pd128(&src, &mut dst),
        "vec_shuffle_w64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_shuffle_w64(&sm, &mut dm, c.encoding); dst.set_qw(0, dm.qw()); },
        "vec_shuffle_lw128" => vec::vec_shuffle_lw128(&src, &mut dst, c.encoding),
        "vec_shuffle_hw128" => vec::vec_shuffle_hw128(&src, &mut dst, c.encoding),
        "vec_shuffle_d128" => vec::vec_shuffle_d128(&src, &mut dst, c.encoding),
        "vec_shuffle_ps128" => vec::vec_shuffle_ps128(&src, &mut dst, c.encoding),
        "vec_shuffle_pd128" => vec::vec_shuffle_pd128(&src, &mut dst, c.encoding),
        "vec_compare_eqb64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_compare_eqb64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_compare_eqw64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_compare_eqw64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_compare_eqd64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_compare_eqd64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_compares_gtb64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_compares_gtb64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_compares_gtw64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_compares_gtw64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_compares_gtd64" => { let sm = MmReg(src.qw(0)); let mut dm = MmReg(dst.qw(0)); vec::vec_compares_gtd64(&sm, &mut dm); dst.set_qw(0, dm.qw()); },
        "vec_compare_eqb128" => vec::vec_compare_eqb128(&src, &mut dst),
        "vec_compare_eqw128" => vec::vec_compare_eqw128(&src, &mut dst),
        "vec_compare_eqd128" => vec::vec_compare_eqd128(&src, &mut dst),
        "vec_compares_gtb128" => vec::vec_compares_gtb128(&src, &mut dst),
        "vec_compares_gtw128" => vec::vec_compares_gtw128(&src, &mut dst),
        "vec_compares_gtd128" => vec::vec_compares_gtd128(&src, &mut dst),
        "vec_movl_p64" => { let s = src.qw(0); vec::vec_movl_p64(&s, &mut dst); },
        "vec_movl_pm64" => { let mut o = 0u64; vec::vec_movl_pm64(&src, &mut o); out[..8].copy_from_slice(&o.to_le_bytes()); },
        "vec_movh_p64" => { let s = src.qw(0); vec::vec_movh_p64(&s, &mut dst); },
        "vec_movh_pm64" => { let mut o = 0u64; vec::vec_movh_pm64(&src, &mut o); out[..8].copy_from_slice(&o.to_le_bytes()); },
        "vec_movmask_b64" => { let sm = MmReg(src.qw(0)); let mut o = 0u32; vec::vec_movmask_b64(&sm, &mut o); out[..4].copy_from_slice(&o.to_le_bytes()); },
        "vec_movmask_b128" => { let mut o = 0u32; vec::vec_movmask_b128(&src, &mut o); out[..4].copy_from_slice(&o.to_le_bytes()); },
        "vec_fmovmask_d128" => { let mut o = 0u32; vec::vec_fmovmask_d128(&src, &mut o); out[..4].copy_from_slice(&o.to_le_bytes()); },
        "vec_insert_w64" => { let s = src.u32(0); let mut dm = MmReg(dst.qw(0)); vec::vec_insert_w64(&s, &mut dm, c.index); dst.set_qw(0, dm.qw()); },
        "vec_insert_w128" => { let s = src.u32(0); vec::vec_insert_w128(&s, &mut dst, c.index); },
        "vec_extract_w128" => { let mut o = 0u32; vec::vec_extract_w128(&src, &mut o, c.index); out[..4].copy_from_slice(&o.to_le_bytes()); },
        "vec_avg_b128" => vec::vec_avg_b128(&src, &mut dst),
        "vec_avg_w128" => vec::vec_avg_w128(&src, &mut dst),
            other => panic!("{other} is in the reference but has no dispatch arm"),
        }

        assert_eq!(dst.bytes(), want_dst, "{}: destination register", ctx());
        assert_eq!(out, want_out, "{}: scalar destination", ctx());
        let got_flags = [
            cpu.zf as u8,
            cpu.cf,
            cpu.pf as u8,
            cpu.of,
            cpu.sf as u8,
            cpu.af as u8,
            cpu.zf_res() as u8,
            cpu.pf_res() as u8,
            cpu.sf_res() as u8,
        ];
        assert_eq!(got_flags, want_flags[..], "{}: cpu flags", ctx());
        compared += 48 + 9;
    }

    assert_eq!(seen.len(), 166, "the reference should exercise all 166 operations");
    println!(
        "{} results matched the C reference exactly ({} operations, {} cases, {} state bytes each)",
        records.len(),
        seen.len(),
        cases.len(),
        compared / records.len()
    );
}

#[test]
fn the_reference_actually_exercises_the_corners() {
    let (cases, records) = parse_fixture();
    // the case table has to carry the parameters the corner cases need
    let amounts: Vec<u8> = cases.iter().map(|c| c.amount).collect();
    for a in [0u8, 1, 15, 16, 31, 32, 63, 64, 127, 255] {
        assert!(amounts.contains(&a), "no case shifts by {a}");
    }
    let types: Vec<u8> = cases.iter().map(|c| c.type_).collect();
    for t in 0u8..8 {
        assert!(types.contains(&t), "no case uses float-compare predicate {t}");
    }
    let indices: Vec<u8> = cases.iter().map(|c| c.index).collect();
    for i in 0u8..8 {
        assert!(indices.contains(&i), "no case uses insert/extract index {i}");
    }

    // the NaN payload of the commutative arithmetic depends on which operand
    // the compiler puts in the destination register, so the corpus has to
    // contain cases where *both* operands are NaN - in both float widths
    let (mut nan64, mut nan32) = (0usize, 0usize);
    for c in &cases {
        let s = XmmReg::from_bytes(c.src);
        let d = XmmReg::from_bytes(c.dst);
        if (0..2).any(|i| s.f64(i).is_nan() && d.f64(i).is_nan()) {
            nan64 += 1;
        }
        if (0..4).any(|i| s.f32(i).is_nan() && d.f32(i).is_nan()) {
            nan32 += 1;
        }
    }
    assert!(nan64 > 0, "no case has both f64 operands NaN");
    assert!(nan32 > 0, "no case has both f32 operands NaN");

    // and the dumps must not be degenerate
    let nonzero = records
        .iter()
        .filter(|r| r[3..19].iter().any(|b| b != "00"))
        .count();
    assert!(
        nonzero > records.len() / 2,
        "only {nonzero} of {} destinations are non-zero",
        records.len()
    );
    let flags_set = records.iter().filter(|r| r[51..60].iter().any(|b| b != "0")).count();
    assert!(flags_set > 0, "no operation ever set a cpu flag");
}
