// Generated from the SICP XML sources by tools/convert.py — do not edit.
#import "../../../lib/sicp.typ": *

#subsection([Implementing the Query System], label-name: <sec:implementing-the-query-system>)

Section @sec:how-query-works described how the query
system works. Now we fill in the details by presenting a complete
implementation of the system.

#subsubsection([The Driver Loop], label-name: <sec:query-driver>)

The
#idx("driver loop", sub: "in query interpreter")
#idx("query interpreter", sub: "driver loop")
driver loop for the query system repeatedly reads input expressions.
If the expression is a rule or assertion to be added to
the data base, then the information is added. Otherwise the
expression is assumed to be a query. The driver passes this query to
#py("evaluate_query")
together with an initial frame stream consisting of a single empty frame.
The result of the evaluation is a stream of frames generated by satisfying
the query with variable values found in the data base. These frames are
used to form a new stream consisting of copies of the original query in
which the variables are instantiated with values supplied by the stream of
frames, and this final stream is
displayed:

#idx("prompts", sub: "query interpreter")#idx("querydriverloop", decl: true)
#snippet(```python
input_prompt = "Query input:"
output_prompt = "Query results:"
def query_driver_loop():
    input = user_read(input_prompt) + ";"
    if is_none(input):
        print("evaluator terminated")
    else:
        expression = parse(input)
        query = convert_to_query_syntax(expression)
        if is_assertion(query):
            add_rule_or_assertion(assertion_body(query))
            print("Assertion added to data base.")
        else:
            print(output_prompt)
            display_stream(stream_map(lambda frame: (unparse(instantiate_expression(expression, frame))), evaluate_query(query, singleton_stream(None))))
        return query_driver_loop()
```)

Here, as in the other evaluators in this chapter, we use
#idx("abstract syntax", sub: "in query interpreter")
#idx("parse", sub: "in query interpreter")
#py("parse") to
transform a component of the query language given as a string
into a Python syntax representation. (We append a
semicolon to the input expression string because
#py("parse") expects a statement.)
Then we further transform the syntax representation
to a conceptual level appropriate
for the query system using
#py("convert_to_query_syntax"),
which is declared in section @sec:query-syntax
along with the predicate
#py("is_assertion")
and the selector
#py("assertion_body").
The function #py("add_rule_or_assertion")
is declared in section @sec:query-db.
The frames resulting from query evaluation are used to instantiate
the syntax representation, and the result is unparsed into a string for
print. The functions
#idx("query interpreter", sub: "instantiation")
#idx("instantiateexpression")
#py("instantiate_expression") and
#idx("unparse", sub: "in query interpreter")
#py("unparse") are declared in
section @sec:query-syntax.

#idx("query interpreter", sub: "instantiation")
#idx("query interpreter", sub: "driver loop")

#subsubsection([The Evaluator], label-name: <sec:query-eval>)

The
#idx("query interpreter", sub: "query evaluator")
#py("evaluate_query")
function,
called by the
#py("query_driver_loop"),
is the basic evaluator of the query system. It takes as inputs a query
and a stream of frames, and it returns a stream of extended frames.
It identifies
syntactic
forms by a
#idx("data-directed programming", sub: "in query interpreter")
data-directed dispatch using #py("get") and
#py("put"), just as we did in implementing generic
operations in chapter @chap:data. Any query that is not identified as a
syntactic
form is assumed to be a simple query, to be processed by
#py("simple_query").
#idx("evaluatequery", decl: true)
#snippet(```python
def evaluate_query(query, frame_stream):
    qfun = get(type(query), "evaluate_query")
    return simple_query(query, frame_stream) if is_none(qfun) else qfun(contents(query), frame_stream)
```)

The functions #py("type")
and #py("contents"), defined in
section @sec:query-syntax, implement
the abstract syntax of the syntactic forms.

#subheading([Simple queries])

#idx("simple query", sub: "processing")

The
#py("simple_query")
function
handles simple queries. It takes as arguments a simple query (a pattern)
together with a stream of frames, and it returns the stream formed by
extending each frame by all data-base matches of the query.
#idx("simplequery", decl: true)
#snippet(```python
def simple_query(query_pattern, frame_stream):
    return stream_flatmap(lambda frame: (stream_append_delayed(find_assertions(query_pattern, frame), lambda : (apply_rules(query_pattern, frame)))), frame_stream)
```)

For each frame in the input stream, we use
#py("find_assertions")
(section @sec:query-match) to match the pattern
against all assertions in the data base, producing a stream of extended
frames, and we use
#py("apply_rules")
(section @sec:query-unify) to apply
all possible rules, producing another stream of extended frames.
These two streams are combined (using
#py("stream_append_delayed"),
section @sec:query-streams) to make a stream of all
the ways that the given pattern can be satisfied consistent with the
original frame (see exercise @ex:q-why-not-append).
The streams for the individual input frames are combined using
#py("stream_flatmap")
(section @sec:query-streams) to form one large stream
of all the ways that any of the frames in the original input stream can be
extended to produce a match with the given pattern.

#idx("simple query", sub: "processing")

#subheading([Compound queries])

#idx("compound query", sub: "processing")

We handle #idx("and (query language)", sub: "evaluation of") #py("and") queries as illustrated in figure @fig:query-and with the
#py("conjoin")
function, which
takes as inputs the conjuncts and the frame stream and returns the stream
of extended frames. First, #py("conjoin") processes
the stream of frames to find the stream of all possible frame extensions
that satisfy the first query in the conjunction. Then, using this as the
new frame stream, it recursively applies
#py("conjoin") to the rest of the queries.
#idx("conjoin", decl: true)
#snippet(```python
def conjoin(conjuncts, frame_stream):
    return frame_stream if is_empty_conjunction(conjuncts) else conjoin(rest_conjuncts(conjuncts), evaluate_query(first_conjunct(conjuncts), frame_stream))
```)

The
statement

#snippet(```python
put("and", "evaluate_query", conjoin)
```)

sets up
#py("evaluate_query")
to dispatch to #py("conjoin") when an
#py("and")

is encountered.

We handle #idx("or (query language)", sub: "evaluation of") #py("or") queries
similarly, as shown in
figure @fig:query-or.
The output streams for the various disjuncts of the
#py("or") are computed separately and merged using
the
#py("interleave_delayed")
function
from section @sec:query-streams.
(See exercises @ex:q-why-not-append
and @ex:q-why-interleave.)
#idx("disjoin", decl: true)
#snippet(```python
def disjoin(disjuncts, frame_stream):
    return None if is_empty_disjunction(disjuncts) else interleave_delayed(evaluate_query(first_disjunct(disjuncts), frame_stream), lambda : (disjoin(rest_disjuncts(disjuncts), frame_stream)))
put("or", "evaluate_query", disjoin)
```)

The predicates and selectors for the
representation
of conjuncts and disjuncts
are given in section @sec:query-syntax.

#subheading([Filters])

The #idx("not (query language)", sub: "evaluation of") #py("not") syntactic form is
handled by the method outlined in
section @sec:how-query-works. We attempt to extend
each frame in the input stream to satisfy the query being negated, and we
include a given frame in the output stream only if it cannot be extended.

#idx("negate", decl: true)
#snippet(```python
def negate(exps, frame_stream):
    return stream_flatmap(lambda frame: (singleton_stream(frame) if is_none(evaluate_query(negated_query(exps), singleton_stream(frame))) else None), frame_stream)
put("not", "evaluate_query", negate)
```)

The #idx("javascriptpredicate (query language)", sub: "evaluation of") #py("javascript_predicate") syntactic form
is a filter similar to #py("not").

Each frame in
the stream is used to instantiate the variables in the predicate, the
instantiated predicate is evaluated, and the frames for which the
predicate evaluates to false are filtered out of the input stream.
The instantiated predicate is evaluated using
#py("evaluate")
from section @sec:mc-eval with
#py("the_global_environment") and
thus can handle any Python expression, as long as all
pattern variables are instantiated prior to evaluation.

#idx("javascriptpredicate (query interpreter)", decl: true)
#snippet(```python
def javascript_predicate(exps, frame_stream):
    return stream_flatmap(lambda frame: (singleton_stream(frame) if evaluate(instantiate_expression(javascript_predicate_expression(exps), frame), the_global_environment) else None), frame_stream)
put("javascript_predicate", "evaluate_query", javascript_predicate)
```)

The
#py("always_true") syntactic form
provides for a query that is always satisfied. It ignores its contents
(normally empty) and simply passes through all the frames in the input
stream.
The #py("rule_body") selector (section @sec:query-syntax) uses #py("always_true")
#idx("rule (query language)", sub: "without body")
to provide bodies for rules that were defined without bodies (that is,
rules whose bodies are always satisfied).
#idx("alwaystrue", decl: true)
#snippet(```python
def always_true(ignore, frame_stream):
    return frame_stream
put("always_true", "evaluate_query", always_true)
```)

The selectors that define the syntax of
#py("not")
and
#py("javascript_predicate")
are given in section @sec:query-syntax.

#idx("compound query", sub: "processing")
#idx("query interpreter", sub: "query evaluator")

#subsubsection([Finding Assertions by Pattern Matching], label-name: <sec:query-match>)

The function #py("find_assertions"),
#idx("query interpreter", sub: "pattern matching")
#idx("pattern matching", sub: "implementation")
called by
#py("simple_query")
(section @sec:query-eval), takes as input a pattern
and a frame. It returns a stream of frames, each extending the given one
by a data-base match of the given pattern. It uses
#py("fetch_assertions")
(section @sec:query-db) to get a stream of all the
assertions in the data base that should be checked for a match against the
pattern and the frame. The reason for
#py("fetch_assertions")
here is that we can often apply simple tests that will eliminate many of
the entries in the data base from the pool of candidates for a successful
match. The system would still work if we eliminated
#py("fetch_assertions")
and simply checked a stream of all assertions in the data base, but
the computation would be less efficient because we would need to make
many more calls to the matcher.
#idx("findassertions", decl: true)
#snippet(```python
def find_assertions(pattern, frame):
    return stream_flatmap(lambda datum: (check_an_assertion(datum, pattern, frame)), fetch_assertions(pattern, frame))
```)

The function #py("check_an_assertion")
takes as arguments a data object
(an assertion),
a pattern, and a frame and
returns either a one-element stream containing the extended frame or
#py("None")
if the match fails.
#idx("checkanassertion", decl: true)
#snippet(```python
def check_an_assertion(assertion, query_pat, query_frame):
    match_result = pattern_match(query_pat, assertion, query_frame)
    return None if match_result == "failed" else singleton_stream(match_result)
```)

The basic pattern matcher returns either the
string #py("\"failed\"")
or an extension of the given frame. The basic idea of the matcher is to
check the pattern against the data, element by element, accumulating
bindings for the pattern variables. If the pattern and the data
object are the same, the match succeeds and we return the frame of
bindings accumulated so far. Otherwise, if the pattern is a variable
(checked by the function #py("is_variable") declared in section @sec:query-syntax)
we extend the current frame by binding the variable to the data, so
long as this is consistent with the bindings already in the frame. If
the pattern and the data are both pairs, we (recursively) match the
head
of the pattern against the
head
of the data to produce a frame; in this frame we then match the
tail
of the pattern against the
tail
of the data. If none of these cases are applicable, the match fails and
we return the
string #py("\"failed\"").
#idx("patternmatch", decl: true)
#snippet(```python
def pattern_match(pattern, data, frame):
    return "failed" if frame == "failed" else frame if pattern == data else extend_if_consistent(pattern, data, frame) if is_variable(pattern) else pattern_match(tail(pattern), tail(data), pattern_match(head(pattern), head(data), frame)) if is_pair(pattern) and is_pair(data) else "failed"
```)

Here is the
function
that extends a frame by adding a new binding, if this is consistent with
the bindings already in the frame:

#idx("extendifconsistent", decl: true)
#snippet(```python
def extend_if_consistent(variable, data, frame):
    binding = binding_in_frame(variable, frame)
    return extend(variable, data, frame) if is_none(binding) else pattern_match(binding_value(binding), data, frame)
```)

If there is no binding for the variable in the frame, we simply add
the binding of the variable to the data. Otherwise we match, in the
frame, the data against the value of the variable in the frame. If
the stored value contains only constants, as it must if it was stored
during pattern matching by
#py("extend_if_consistent"),
then the match simply tests whether the stored and new values are the
same. If so, it returns the unmodified frame; if not, it returns a failure
indication. The stored value may, however, contain pattern variables
if it was stored during unification (see
section @sec:query-unify). The recursive match of the
stored pattern against the new data will add or check bindings for the
variables in this pattern. For example, suppose we have a frame in which
#py("$x")
is bound to
#py("llist(\"f\", $y)")
and
#py("$y")
is unbound, and we wish to augment this frame by a binding of
#py("$x")
to
#py("llist(\"f\", \"b\")").
We look up
#py("$x")
and find that it is bound to
#py("llist(\"f\", $y)").
This leads us to match
#py("llist(\"f\", $y)")
against the proposed new value
#py("llist(\"f\", \"b\")")
in the same frame. Eventually this match extends the frame by adding a
binding of
#py("$y")
to
#py("\"b\"").
The variable #py("$x")
remains bound to
#py("llist(\"f\", $y)").
We never modify a stored binding and we never store more than one binding
for a given variable.

The
functions
used by
#py("extend_if_consistent")
to manipulate bindings are defined in
section @sec:query-bindings.

#idx("query interpreter", sub: "pattern matching")
#idx("pattern matching", sub: "implementation")

#subsubsection([Rules and Unification], label-name: <sec:query-unify>)

#idx("rule (query language)", sub: "applying")

The function #py("apply_rules")
is the rule analog of
#py("find_assertions")
(section @sec:query-match). It takes as input a
pattern and a frame, and it forms a stream of extension frames by applying
rules from the data base.
The function #py("stream_flatmap")
maps
#py("apply_a_rule")
down the stream of possibly applicable rules (selected by
#py("fetch_rules"),
section @sec:query-db) and combines the resulting
streams of frames.

#idx("applyrules", decl: true)
#snippet(```python
def apply_rules(pattern, frame):
    return stream_flatmap(lambda rule: (apply_a_rule(rule, pattern, frame)), fetch_rules(pattern, frame))
```)

The function #py("apply_a_rule") applies a rule
using the method outlined in
section @sec:how-query-works. It first augments its
argument frame by unifying the rule conclusion with the pattern in the
given frame. If this succeeds, it evaluates the rule body in this new
frame.

Before any of this happens, however, the program renames all the variables
in the rule with unique new names. The reason for this is to prevent the
variables for different rule applications from becoming confused with each
other. For instance, if two rules both use a variable
named #py("$x"),
then each one may add a binding for
#py("$x")
to the frame when it is applied. These two
#py("$x")'s
have nothing to do with each other, and we should not be fooled into
thinking that the two bindings must be consistent. Rather than rename
variables, we could devise a more clever environment structure; however,
the renaming approach we have chosen here is the most straightforward,
even if not the most efficient. (See
exercise @ex:query-local-names.) Here is the
#py("apply_a_rule")
function:
#idx("applyarule", decl: true)
#snippet(```python
def apply_a_rule(rule, query_pattern, query_frame):
    clean_rule = rename_variables_in(rule)
    unify_result = unify_match(query_pattern, conclusion(clean_rule), query_frame)
    return None if unify_result == "failed" else evaluate_query(rule_body(clean_rule), singleton_stream(unify_result))
```)

The selectors
#py("rule_body")
and #py("conclusion") that extract parts
of a rule are defined in section @sec:query-syntax.

We generate unique variable names by associating a unique identifier
(such as a number) with each rule application and combining this
identifier with the original variable names. For example, if the
rule-application identifier is 7, we might change each
#py("$x")
in the rule to
#py("$x_7")
and each
#py("$y")
in the rule to
#py("$y_7").
(The functions #py("make_new_variable")
and
#py("new_rule_application_id")
are included with the syntax
functions
in section @sec:query-syntax.)
#idx("renamevariablesin", decl: true)
#snippet(```python
def rename_variables_in(rule):
    rule_application_id = new_rule_application_id()
    def tree_walk(exp):
        return make_new_variable(exp, rule_application_id) if is_variable(exp) else pair(tree_walk(head(exp)), tree_walk(tail(exp))) if is_pair(exp) else exp
    return tree_walk(rule)
```)

#idx("rule (query language)", sub: "applying")

The
#idx("query interpreter", sub: "unification")
#idx("unification", sub: "implementation")
unification algorithm is implemented as a
function
that takes as inputs two patterns and a frame and returns either the
extended frame or the
string #py("\"failed\"").
The unifier is like the pattern matcher except that it is
symmetrical—variables are allowed on both sides of the match.
The function #py("unify_match")
is basically the same as
#py("pattern_match"),
except that there is
an extra clause
(marked
"\*\*\*" below) to handle
the case where the object on the right side of the match is a variable.
#idx("unifymatch", decl: true)
#snippet(```python
def unify_match(p1, p2, frame):
    return "failed" if frame == "failed" else frame if p1 == p2 else extend_if_possible(p1, p2, frame) if is_variable(p1) else extend_if_possible(p2, p1, frame) if is_variable(p2) else unify_match(tail(p1), tail(p2), unify_match(head(p1), head(p2), frame)) if is_pair(p1) and is_pair(p2) else "failed"
```)

In unification, as in one-sided pattern matching, we want to accept a
proposed extension of the frame only if it is consistent with existing
bindings. The
function
#py("extend_if_possible")
used in unification is the same as the
function #py("extend_if_consistent")
used in pattern matching except for two special checks, marked
"\*\*\*" in the program below. In
the first case, if the variable we are trying to match is not bound, but
the value we are trying to match it with is itself a (different) variable,
it is necessary to check to see if the value is bound, and if so, to match
its value. If both parties to the match are unbound, we may bind either
to the other.

The second check deals with attempts to bind a variable to a pattern
that includes that variable. Such a situation can occur whenever a
variable is repeated in both patterns. Consider, for example,
unifying the two patterns
#py("llist($x, $x)")
and
#py("llist($y,") $⟨$#meta("expression") #meta("involving") #py("$y")$⟩$#py(")")
in a frame where both
#py("$x")
and
#py("$y")
are unbound. First
#py("$x")
is matched against
#py("$y"),
making a binding of
#py("$x")
to
#py("$y").
Next, the same
#py("$x")
is matched against the given
expression involving
#py("$y").
Since
#py("$x")
is already bound to
#py("$y"),
this results in matching
#py("$y")
against the
expression.
If we think of the unifier as finding a set of
values for the pattern variables that make the patterns the same, then
these patterns imply instructions to find a
#py("$y")
such that
#py("$y")
is equal to the expression involving
#py("$y").
We
reject such
bindings; these cases are recognized by the predicate
#py("depends_on").#footnote[In general,
unifying
#py("$y") with an expression involving
#py("$y")
would require our being able to find a
#idx("fixed point", sub: "unification and")
fixed point of the equation
#py("$y") $= ⟨$#meta("expression") #meta("involving") #py("$y")$⟩$.
It is sometimes possible to syntactically form an expression that appears to be the solution. For example, #py("$y")
$=$
#py("llist(\"f\", $y)")
seems to have the fixed point
#py("llist(\"f\", llist(\"f\", llist(\"f\",") … #py(")))"),
which we can produce by beginning with the expression
#py("llist(\"f\", $y)")
and repeatedly substituting
#py("llist(\"f\", $y)")
for
#py("$y").
Unfortunately, not every such equation has a meaningful fixed point. The
issues that arise here are similar to the issues of manipulating
#idx("infinite series")
infinite series in mathematics. For example, we know that 2 is the
solution to the equation $y = 1 + y/2$.
Beginning with the expression $1 + y/2$ and
repeatedly substituting $1 + y/2$ for
$y$ gives

$ 2 space = space y space = space 1 + y/2 space = space 1 + (1+y/2)/2 space = space 1 + 1/2 + y/4 space = space dots.c , $

which leads to

$ 2 space = space 1 + 1/2 + 1/4 + 1/8 + dots.c . $

However, if we try the same manipulation beginning with the
observation that $-1$ is the solution to the
equation $y space = space 1 + 2y$, we obtain

$ -1 space = space y space = space 1 + 2y space = space 1 + 2(1 + 2y) space = space 1 + 2 + 4y space = space dots.c , $

which leads to

$ -1 space = space 1 + 2 + 4 + 8 + dots.c . $

Although the formal manipulations used in deriving these two equations
are identical, the first result is a valid assertion about infinite
series but the second is not. Similarly, for our unification results,
reasoning with an arbitrary syntactically constructed expression may
lead to errors.

Nevertheless, most logic programming systems today allow
cyclic references, by accepting the cyclic data structure
as the result of the match. This is justified
theoretically using #emph[rational trees]
#idx("Jaffar, Joxan")
#idx("Stuckey, Peter J.")
#idx("tree", sub: "rational")
#idx("rational tree")
(Jaffar and Stuckey 1986).
Accepting
a cyclic data structure allows self-referential data, such
as an employee data structure that refers to the employer,
which in turn refers to the employee.]
On the other hand, we do not want to reject attempts
to bind a variable to itself. For example, consider unifying
#py("llist($x, $x)")
and
#py("llist($y, $y)").
The second attempt to bind
#py("$x")
to
#py("$y")
matches
#py("$y")
(the stored value of #py("$x"))
against
#py("$y")
(the new value of #py("$x")
This is taken care of by the
#py("equal")
clause of
#py("unify_match").

#idx("extendifpossible", decl: true)
#snippet(```python
def extend_if_possible(variable, value, frame):
    binding = binding_in_frame(variable, frame)
    if  not  is_none(binding):
        return unify_match(binding_value(binding), value, frame)
    elif is_variable(value):
        binding = binding_in_frame(value, frame)
        return unify_match(variable, binding_value(binding), frame) if not is_none(binding) else extend(variable, value, frame)
    elif depends_on(value, variable, frame):
        return "failed"
    else:
        return extend(variable, value, frame)
```)

The function #py("depends_on")
is a predicate that tests whether an expression proposed to be the value
of a pattern variable depends on the variable. This must be done relative
to the current frame because the expression may contain occurrences of a
variable that already has a value that depends on our test variable.
The structure of
#py("depends_on")
is a simple recursive tree walk in which we substitute for the values of
variables whenever necessary.
#idx("dependson", decl: true)
#snippet(```python
def depends_on(expression, variable, frame):
    def tree_walk(e):
        if is_variable(e):
            if variable == e:
                return True
            else:
                b = binding_in_frame(e, frame)
                return False if is_none(b) else tree_walk(binding_value(b))
        else:
            return tree_walk(head(e)) or tree_walk(tail(e)) if is_pair(e) else False
    return tree_walk(expression)
```)

#idx("query interpreter", sub: "unification")
#idx("unification", sub: "implementation")

#subsubsection([Maintaining the Data Base], label-name: <sec:query-db>)

One important problem in designing logic programming languages is that
of arranging things so that as few irrelevant
#idx("query interpreter", sub: "data base")
#idx("data base", sub: "indexing")
#idx("indexing a data base")
data-base entries as
possible will be examined in checking a given pattern. For this purpose,
we will represent an assertion as a list whose head is a string that
represents the kind of information of the assertion.
We store the assertions in separate streams, one for each kind of information, in a table indexed by the kind. To fetch an assertion that may match a pattern, we return (to be tested using the matcher) all the stored assertions that have the same head (the same kind of information). Cleverer methods could also take advantage of information in the frame. We avoid building our criteria for indexing into the program instead we call on predicates and selectors that embody our criteria.
#idx("fetchassertions", decl: true)
#snippet(```python
def fetch_assertions(pattern, frame):
    return get_indexed_assertions(pattern)
def get_indexed_assertions(pattern):
    return get_stream(index_key_of(pattern), "assertion-stream")
```)

The function #py("get_stream")
looks up a stream in the table and returns an empty stream if nothing is
stored there.

#snippet(```python
def get_stream(key1, key2):
    s = get(key1, key2)
    return None if is_none(s) else s
```)

Rules are stored similarly, using the head
of the rule conclusion.
A pattern
can match rules whose conclusions have the same head.
Thus, when fetching rules that might match a pattern
we fetch all rules whose conclusions have the same head
as the pattern.

#idx("fetchrules", decl: true)
#snippet(```python
def fetch_rules(pattern, frame):
    return get_indexed_rules(pattern)
def get_indexed_rules(pattern):
    return get_stream(index_key_of(pattern), "rule-stream")
```)

The function #py("add_rule_or_assertion")
is used by
#py("query_driver_loop")
to add assertions and rules to the data base. Each item is stored in the
index.
#idx("addruleorassertion", decl: true)
#snippet(```python
def add_rule_or_assertion(assertion):
    return add_rule(assertion) if is_rule(assertion) else add_assertion(assertion)
def add_assertion(assertion):
    store_assertion_in_index(assertion)
    return "ok"
def add_rule(rule):
    store_rule_in_index(rule)
    return "ok"
```)

To actually store an assertion or a rule, we store it in the appropriate stream.

#snippet(```python
def store_assertion_in_index(assertion):
    key = index_key_of(assertion)
    current_assertion_stream = get_stream(key, "assertion-stream")
    put(key, "assertion-stream", pair(assertion, lambda : (current_assertion_stream)))
def store_rule_in_index(rule):
    pattern = conclusion(rule)
    key = index_key_of(pattern)
    current_rule_stream = get_stream(key, "rule-stream")
    put(key, "rule-stream", pair(rule, lambda : (current_rule_stream)))
```)

The key under which a pattern
(an assertion or rule conclusion)
is stored in the table is the
string it starts with.

#snippet(```python
def index_key_of(pattern):
    return head(pattern)
```)

#idx("query interpreter", sub: "data base")

#subsubsection([Stream Operations], label-name: <sec:query-streams>)

#idx("query interpreter", sub: "stream operations")

The query system uses a few stream operations that were not presented
in chapter @chap:state.

The functions #py("stream_append_delayed")
and
#py("interleave_delayed")
are just like
#py("stream_append")
and
#py("interleave")
(section @sec:exploiting-streams),
except that they take a delayed argument (like the
#py("integral")
function
in section @sec:streams-and-delayed-evaluation).
This postpones looping in some cases (see
exercise @ex:q-why-not-append).
#idx("streamappenddelayed", decl: true)#idx("interleavedelayed", decl: true)
#snippet(```python
def stream_append_delayed(s1, delayed_s2):
    return delayed_s2() if is_none(s1) else pair(head(s1), lambda : (stream_append_delayed(stream_tail(s1), delayed_s2)))
def interleave_delayed(s1, delayed_s2):
    return delayed_s2() if is_none(s1) else pair(head(s1), lambda : (interleave_delayed(delayed_s2(), lambda : (stream_tail(s1)))))
```)

The function #py("stream_flatmap"),
which is used throughout the query evaluator to map a
function
over a stream of frames and combine the resulting streams of frames,
is the stream analog of the #py("flatmap")
function
introduced for ordinary lists in
section @sec:nested-mappings. Unlike ordinary
#py("flatmap"), however, we accumulate the streams
with an interleaving process, rather than simply appending them (see
exercises @ex:q-why-interleave
and @ex:q-why-delay).
#idx("streamflatmap", decl: true)#idx("flattenstream", decl: true)
#snippet(```python
def stream_flatmap(fun, s):
    return flatten_stream(stream_map(fun, s))
def flatten_stream(stream):
    return None if is_none(stream) else interleave_delayed(head(stream), lambda : (flatten_stream(stream_tail(stream))))
```)

The evaluator also uses the following simple
function
to generate a stream consisting of a single element:
#idx("singletonstream", decl: true)
#snippet(```python
def singleton_stream(x):
    return pair(x, lambda : (None))
```)

#idx("query interpreter", sub: "stream operations")

#subsubsection([Query Syntax Functions and Instantiation], label-name: <sec:query-syntax>)

#idx("query interpreter", sub: "syntax of query language")
#idx("query-language-specific representation")

We saw in section @sec:query-driver that
the driver loop first transforms an input string into the Python
syntax representation.
The input is designed to look like a
Python expression so that we can use the
#py("parse") function
from section @sec:representing-expressions and
also to support Python notation in
#py("javascript_predicate").
For example,

#snippet(```python
parse('job($x, list("computer", "wizard"));')
```)

yields

#output(```python
parse('job($x, list("computer", "wizard"));')
```)

The tag
#py("\"application\"") indicates that
syntactically,
the query would be treated as a function application in JavaScipt.
The function
#py("unparse") transforms the syntax
back into a string:

#snippet(```python
unparse(parse('job($x, list("computer", "wizard"));'))
```)

#output(```python
unparse(parse('job($x, list("computer", "wizard"));'))
```)

In the query processor, we assumed a
query-language-specific
representation of assertions, rules, and queries.
The function
#py("convert_to_query_syntax")
transforms the syntax representation into that representation.
Using the same example,

#snippet(```python
convert_to_query_syntax(parse('job($x, list("computer", "wizard"));'))
```)

yields

#output(```python
convert_to_query_syntax(parse('job($x, list("computer", "wizard"));'))
```)

Query-system functions such as
#py("add_rule_or_assertion")
in section @sec:query-db
and
#py("evaluate_query")
in section @sec:query-eval
operate on the query-language-specific representation using
selectors and predicates such as
#py("type"),
#py("contents"),
#py("is_rule"), and
#py("first_conjunct") declared below.
Figure @fig:syntax-abstraction-lp depicts the three
#idx("abstraction barriers", sub: "in query language")
abstraction barriers used by the query system and how the transformation functions
#py("parse"),
#py("unparse"), and
#py("convert_to_query_syntax") bridge them.

#sicp-figure(image("/images/img_javascript/ch4-syntax-abstraction-logic-programming.svg", width: 70%), caption: [Syntax abstraction in the query system.], label-name: <fig:syntax-abstraction-lp>)

#subheading([Handling pattern variables])

The predicate
#py("is_variable") is used on the
query-language-specific representation during query processing and
on the Python syntax representation during instantiation
to identify names that start with a dollar sign.
#idx("query interpreter", sub: "pattern-variable representation")
#idx("pattern variable", sub: "representation of")
We assume there is a function #py("char_at") that
returns a string containing only the character of the given string
at the given position.#footnote[The actual way to get the string that
contains the first
character of a string #py("s") in JavaScript is
#py("s.charAt(0)").]
#idx("isvariable", sub: "in query system", decl: true)
#snippet(```python
def is_variable(exp):
    return is_name(exp) and char_at(symbol_of_name(exp), 0) == "$"
```)

Unique variables are constructed during rule application
(in section @sec:query-unify) by means of the
following functions.
The unique identifier for a rule application is a number, which is
incremented each time a rule is applied.#footnote[Creating
new variables with string concatenation and identifying
variables by checking their first character during query
processing is somewhat wasteful. A more efficient solution
would mark pattern variables with a separate tag in the
query-language-specific representation and use pair
construction rather than string concatenation to create
new variables. We chose the less efficient solution
to simplify the presentation.]
#idx("makenewvariable", decl: true)
#snippet(```python
rule_counter = 0
def new_rule_application_id():
    rule_counter = rule_counter + 1
    return rule_counter
def make_new_variable(variable, rule_application_id):
    return make_name(symbol_of_name(variable) + "_" + stringify(rule_application_id))
```)

#subheading([The function #py("convert_to_query_syntax")])

The function #py("convert_to_query_syntax")
recursively
#idx("query-language-specific representation", sub: "transforming Python syntax into")
transforms the Python syntax representation into
the query-language-specific representation by simplifying
assertions, rules, and queries such that the symbol of a name in a
function expression of an application becomes a tag, except that if
the symbol is #py("\"pair\"")
or #py("\"list\""), an (untagged) Python pair
or list is built. This means that
#py("convert_to_query_syntax")
interprets
applications of
the constructors #py("pair") and
#py("list") during the transformation,
and processing functions such as
#py("pattern_match")
of section @sec:query-match and
#py("unify_match")
of section @sec:query-unify
can operate directly on the intended pairs and
lists rather than on the syntax representation generated by the parser.
The (one-element) "argument" list of
#py("javascript_predicate")
remains unprocessed, as explained below.
A variable remains unchanged, and
a literal is simplified to the primitive value it contains.
#idx("converttoquerysyntax", decl: true)
#snippet(```python
def convert_to_query_syntax(exp):
    if is_application(exp):
        function_symbol = symbol_of_name(function_expression(exp))
        if function_symbol == "javascript_predicate":
            return pair(function_symbol, arg_expressions(exp))
        else:
            processed_args = map(convert_to_query_syntax, arg_expressions(exp))
            return pair(head(processed_args), head(tail(processed_args))) if function_symbol == "pair" else processed_args if function_symbol == "list" else pair(function_symbol, processed_args)
    elif is_variable(exp):
        return exp
    else:
        return literal_value(exp)
```)

An exception to this processing is
#py("javascript_predicate").
Since the instantiated Python syntax
representation
of its predicate expression is passed to
#py("evaluate")
of section @sec:core-of-evaluator,
the original syntax representation coming from
#py("parse")
needs to remain intact in the query-language-specific representation
of the expression.
In this example
of section @sec:deductive-info-retrieval

#snippet(```python
and(salary($person, $amount), javascript_predicate($amount > 50000))
```)

#py("convert_to_query_syntax") produces a data structure
in which a Python syntax representation is embedded in
a query-language-specific representation:

#output(```python
and(salary($person, $amount), javascript_predicate($amount > 50000))
```)

In order to evaluate the #py("javascript_predicate") subexpression
of that processed query, the function
#py("javascript_predicate") in
section @sec:query-eval calls the function
#py("instantiate_expression") (below)
on the embedded Python syntax
representation of #py("$amount > 50000") to
replace the variable
#py("list(\"name\", \"$amount\")") by a literal,
for example #py("list(\"literal\", 70000)"), that represents
the primitive value to which
#py("$amount") is bound, here 70000.
The Python evaluator can evaluate the instantiated predicate, which now represents
#py("70000 > 50000").

#subheading([Instantiating an expression])

#idx("query interpreter", sub: "instantiation")

The function #py("javascript_predicate")
of section @sec:query-eval and the driver loop
of section @sec:query-driver call
#py("instantiate_expression") on an
expression to obtain a copy in which any variable in the
expression is replaced by its value in a given frame.
The input and result expressions use the Python syntax
representation, so any value that results from instantiating a
variable needs to be converted from its form in the binding to
the Python syntax representation.
#idx("instantiateexpression", decl: true)
#snippet(```python
def instantiate_expression(expression, frame):
    return convert(instantiate_term(expression, frame)) if is_variable(expression) else pair(instantiate_expression(head(expression), frame), instantiate_expression(tail(expression), frame)) if is_pair(expression) else expression
```)

The function
#py("instantiate_term") takes
a variable, pair, or primitive value as first argument and a frame
as second argument and recursively replaces the variables in
the first argument by their values in the frame
until a primitive value or an unbound variable is reached.
When the process encounters a pair, a new pair is constructed
whose parts are the instantiated versions of the original parts.
For example, if
#py("$x")
is bound to the pair
$[mono("$y"), 5]$
in a frame $f$
as the result of unification, and
#py("$y")
is in turn bound to 3,
the result of applying
#py("instantiate_term") to
#py("list(\"name\", \"$x\")") and
$f$ is the pair
$[3, 5]$.
#idx("instantiateterm", decl: true)
#syntax("
def instantiate_term(term, frame):
    if is_variable(term):
        binding = binding_in_frame(term, frame)
        return term if is_none(binding) else instantiate_term(binding_value(binding), frame)
    elif is_pair(term):
        return pair(instantiate_term(head(term), frame), instantiate_term(tail(term), frame))
    else:
        return term
")

The function
#py("convert")
constructs a Python syntax representation for a variable,
pair, or primitive value returned by
#py("instantiate_term").
A pair in the original becomes an application of Python's
pair constructor and a primitive value becomes a literal.
#idx("convert", decl: true)
#syntax("
def convert(term):
    return term if is_variable(term) else make_application(make_name(\"pair\"), llist(convert(head(term)), convert(tail(term)))) if is_pair(term) else make_literal(term)
")

To illustrate these three functions, consider what happens when the query

#snippet(```python
job($x, llist("computer", "wizard"))
```)

whose Python syntax representation is given
at the beginning of section @sec:query-syntax, is
processed by the driver loop.
Let's say a frame $g$ of the result stream
binds the variable
#py("$x") to the pair
$[mono("\"Bitdiddle\""), mono("$y")]$ and
the variable #py("$y") to the pair
$[mono("\"Ben\""), mono("null")]$. Then

#syntax("
instantiate_term(llist(\"name\", \"$\\$$x\"), ", meta("g"), ")
	    ")

returns the list

#output(```python
job($x, llist("computer", "wizard"))
```)

which
#py("convert") transforms into

#output(```python
job($x, llist("computer", "wizard"))
```)

The result of
#py("instantiate_expression")
applied to the Python syntax representation of the query and
the frame $g$ is:

#output(```python
job($x, llist("computer", "wizard"))
```)

The driver loop unparses this representation and displays it as:

#output(```python
job($x, llist("computer", "wizard"))
```)

#idx("query interpreter", sub: "instantiation")

#subheading([The function #py("unparse")])

The function #py("unparse")
transforms a component given in the Python syntax representation
into a string by applying the syntax rules
of section @sec:representing-expressions.
We describe #py("unparse") only for
those kinds of expressions that appear in the examples of
section @sec:deductive-info-retrieval, leaving statements
and the remaining kinds of expressions
as exercise @ex:parse. A literal is transformed by
#py("stringify")ing its value, and
a name is transformed into its
#idx("symbol(s)", sub: "in unparse")
symbol.
An application is formatted by unparsing the function expression,
which we can assume to be a name here, followed by the comma-separated
argument expression strings enclosed in parentheses.
Binary operator combinations are formatted using infix notation.
#idx("unparse", sub: "in query interpreter", decl: true)
#syntax("
function unparse(exp) {
    return is_literal(exp)
           ? stringify(literal_value(exp))
           : is_name(exp)
           ? symbol_of_name(exp)
           : is_list_construction(exp)
           ? unparse(make_application(make_name(\"list\"),
                                      element_expressions(exp)))
           : is_application(exp) && is_name(function_expression(exp))
           ? symbol_of_name(function_expression(exp)) +
                 \"(\" +
                 comma_separated(map(unparse, arg_expressions(exp))) +
                 \")\"
           : is_binary_operator_combination(exp)
           ? \"(\" + unparse(first_operand(exp)) +
             \" \" + operator_symbol(exp) +
             \" \" + unparse(second_operand(exp)) +
             \")\"
           ", metaphrase[unparsing other kinds of Python components], "
           : error(exp, \"unknown syntax -- unparse\")
}
	    ")

#snippet(```python
def comma_separated(strings):
    return reduce(lambda s, acc: (s + ("" if acc == "" else ", " + acc)), "", strings)
```)

The function
#py("unparse")
would work fine without the clause

#snippet(```python
: is_list_construction(exp)
? unparse(make_application(make_name("list"),
                           element_expressions(exp)))
```)

but the output string would be unnecessarily
verbose in cases where pattern variables are instantiated
by lists. In the example above, where processing the query

#snippet(```python
job($x, llist("computer", "wizard"))
```)

yields a frame that binds
#py("$x")
to $[mono("\"Bitdiddle\""), [mono("\"Ben\""), mono("null")]]$,
#py("unparse") produces

#output(```python
job($x, llist("computer", "wizard"))
```)

However, without the clause it would produce

#output(```python
job($x, llist("computer", "wizard"))
```)

which explicitly constructs the two pairs that make up the first list.
To achieve the more concise formatting used throughout
section @sec:deductive-info-retrieval,
we inserted the clause to check
if the expression constructs a list, in which case
we format it as a single application of
#py("list") to the list of element
expressions that we extract from the expression.
A list construction is the literal
#py("null") or
an application of
#py("pair")
whose second argument is itself a list construction.
#idx("islistconstruction", decl: true)
#snippet(```python
def is_list_construction(exp):
    return (is_literal(exp) and is_none(literal_value(exp))) or (is_application(exp) and is_name(function_expression(exp)) and symbol_of_name(function_expression(exp)) == "pair" and is_list_construction(head(tail(arg_expressions(exp)))))
```)

Extracting the element expressions from a given list construction
amounts to collecting the first arguments of applications of
#py("pair") until the literal
#py("null") is reached.
#idx("elementexpressions", decl: true)
#syntax("
def element_expressions(list_constr):
    return None if is_literal(list_constr) else pair(head(arg_expressions(list_constr)), element_expressions(head(tail(arg_expressions(list_constr)))))
")

#subheading([Predicates and selectors for the query-language-specific representation])

The functions #py("type")
and #py("contents"), used by
#py("evaluate_query")
(section @sec:query-eval), specify that a
syntactic form of a query-language-specific representation
is identified by
the string in its head.
They are the same as the
#py("type_tag")
and #py("contents")
functions
in section @sec:manifest-types, except for the
error message.
#idx("type in query system", decl: true)#idx("contents", decl: true)
#snippet(```python
def type(exp):
    return head(exp) if is_pair(exp) else error("unknown expression type", exp)
def contents(exp):
    return tail(exp) if is_pair(exp) else error("unknown expression contents", exp)
```)

The following functions, used by
#py("query_driver_loop")
(in section @sec:query-driver),
specify that rules and assertions are added to the data base by an
#py("assert") command, which the function
#py("convert_to_query_syntax") transforms
into a pair of the form
#py("[\"assert\",")#meta("rule-or-assertion")#py("]"):
#idx("isassertion", decl: true)#idx("assertionbody", decl: true)
#snippet(```python
def is_assertion(exp):
    return type(exp) == "assert"
def assertion_body(exp):
    return head(contents(exp))
```)

Here are the declarations of the predicates and selectors
for the #py("and"),
#py("or"), #py("not"), and
#py("javascript_predicate")
syntactic forms
(section @sec:query-eval):
#idx("isemptyconjunction", decl: true)#idx("firstconjunct", decl: true)#idx("restconjuncts", decl: true)#idx("isemptydisjunction", decl: true)#idx("firstdisjunct", decl: true)#idx("restdisjuncts", decl: true)#idx("negatedquery", decl: true)#idx("javascriptpredicateexpression", decl: true)
#snippet(```python
def is_empty_conjunction(exps):
    return is_none(exps)

def first_conjunct(exps):
    return head(exps)

def rest_conjuncts(exps):
    return tail(exps)
def is_empty_disjunction(exps):
    return is_none(exps)

def first_disjunct(exps):
    return head(exps)

def rest_disjuncts(exps):
    return tail(exps)
def negated_query(exps):
    return head(exps)
def javascript_predicate_expression(exps):
    return head(exps)
```)

The following three
functions
define the query-language-specific representation of rules:
#idx("isrule", decl: true)#idx("conclusion", decl: true)#idx("rulebody", decl: true)
#snippet(```python
def is_rule(assertion):
    return is_tagged_list(assertion, "rule")
def conclusion(rule):
    return head(tail(rule))

def rule_body(rule):
    return llist("always_true") if is_none(tail(tail(rule))) else head(tail(tail(rule)))
```)

#idx("query interpreter", sub: "syntax of query language")
#idx("query-language-specific representation")

#subsubsection([Frames and Bindings], label-name: <sec:query-bindings>)

#idx("query interpreter", sub: "frame")
#idx("frame (query interpreter)", sub: "representation")

Frames are represented as lists of bindings, which are
variable-value pairs:
#idx("makebinding", decl: true)#idx("bindingvariable", decl: true)#idx("bindingvalue", decl: true)#idx("bindinginframe", decl: true)#idx("extend", decl: true)
#snippet(```python
def make_binding(variable, value):
    return pair(variable, value)
def binding_variable(binding):
    return head(binding)
def binding_value(binding):
    return tail(binding)
def binding_in_frame(variable, frame):
    return assoc(variable, frame)
def extend(variable, value, frame):
    return pair(make_binding(variable, value), frame)
```)

#idx("query interpreter", sub: "frame")

#exercise(label-name: <ex:q-why-not-append>, [
Louis Reasoner wonders why the
#py("simple_query")
and #py("disjoin")
functions
(section @sec:query-eval) are implemented using
delayed expressions
rather than being defined as follows:

#idx("simplequery", sub: "without delayed expression", decl: true)#idx("disjoin", sub: "without delayed expression", decl: true)
#snippet(```python
def simple_query(query_pattern, frame_stream):
    return stream_flatmap(lambda frame: (stream_append(find_assertions(query_pattern, frame), apply_rules(query_pattern, frame))), frame_stream)
def disjoin(disjuncts, frame_stream):
    return None if is_empty_disjunction(disjuncts) else interleave(evaluate_query(first_disjunct(disjuncts), frame_stream), disjoin(rest_disjuncts(disjuncts), frame_stream))
```)

Can you give examples of queries where these simpler definitions would
lead to undesirable behavior?
])

#exercise(label-name: <ex:q-why-interleave>, [
Why do #py("disjoin") and
#py("stream_flatmap")
interleave the streams rather than simply append them? Give examples that
illustrate why interleaving works better. (Hint: Why did we use
#py("interleave") in
section @sec:exploiting-streams?)
])

#exercise(label-name: <ex:q-why-delay>, [
Why does
#py("flatten_stream")
use
a delayed expression in its body?
What would be wrong with defining it as follows:

#snippet(```python
def flatten_stream(stream):
    return None if is_none(stream) else interleave(head(stream), flatten_stream(stream_tail(stream)))
```)
])

#exercise(label-name: <ex:4_71>, [
Alyssa P. Hacker proposes to use a simpler version of
#idx("streamflatmap")
#py("stream_flatmap")
in #py("negate"),
#py("javascript_predicate"),
and
#py("find_assertions").
She observes that the
function
that is mapped over the frame stream in these cases always produces either
the empty stream or a singleton stream, so no interleaving is needed when
combining these streams.

+ Fill in the missing expressions in Alyssa's program. #syntax(" function simple_stream_flatmap(fun, s) { return simple_flatten(stream_map(fun, s)) } function simple_flatten(stream) { return stream_map(", metaphrase[??], ", stream_filter(", metaphrase[??], ", stream)) } ")
+ Does the query system's behavior change if we change it in this way?
])

#exercise(label-name: <ex:unique>, [
Implement for the query language a
#idx("query language", sub: "extensions to")
#idx("compound query", sub: "processing")
#idx("unique (query language)")
syntactic form called #py("unique").
Applictions of #py("unique")
should succeed if there is precisely one item in the data base satisfying
a specified query. For example,

#snippet(```python
unique(job($x, llist("computer", "wizard")))
```)

should print the one-item stream

#snippet(```python
unique(job(llist("Bitdiddle", "Ben"), llist("computer", "wizard")))
```)

since Ben is the only computer wizard, and

#snippet(```python
unique(job($x, llist("computer", "programmer")))
```)

should print the empty stream, since there is more than one computer
programmer. Moreover,

#snippet(```python
and(job($x, $j), unique(job($anyone, $j)))
```)

should list all the jobs that are filled by only one person, and the
people who fill them.

There are two parts to implementing #py("unique").
The first is to write a
function
that handles this
syntactic
form, and the second is to make
#py("evaluate_query")
dispatch to that
function.
The second part is trivial, since
#py("evaluate_query")
does its dispatching in a data-directed way. If your
function
is called
#py("uniquely_asserted"),
all you need to do is

#snippet(```python
put("unique", "evaluate_query", uniquely_asserted)
```)

and
#py("evaluate_query")
will dispatch to this
function
for every query whose
#py("type")
(head)
is the
string
#py("\"unique\"").

The real problem is to write the
function
#py("uniquely_asserted").
This should take as input the #py("contents")
(tail)
of the #py("unique") query, together with a stream
of frames. For each frame in the stream, it should use
#py("evaluate_query")
to find the stream of all extensions to the frame that satisfy the given
query. Any stream that does not have exactly one item in it should be
eliminated. The remaining streams should be passed back to be accumulated
into one big stream that is the result of the
#py("unique") query. This is similar to the
implementation of the #py("not")
syntactic
form.

Test your implementation by forming a query that lists all people who
supervise precisely one person.
])

#exercise(label-name: <ex:q-exponential-and>, [
Our implementation of #py("and") as a series
combination of queries
#idx("query interpreter", sub: "improvements to")
#idx("and (query language)", sub: "evaluation of")
#idx("compound query", sub: "processing")
(figure @fig:query-and)
is
elegant, but it is inefficient because in processing the second query of
the #py("and") we must scan the data base for each
frame produced by the first query. If the data base has
$N$ elements, and a typical query produces a
number of output frames proportional to $N$
(say $N/k$), then scanning the data base for
each frame produced by the first query will require
$N^(2)/k$ calls to the pattern matcher.
Another approach would be to process the two clauses of the
#py("and") separately, then look for all pairs of
output frames that are compatible. If each query produces
$N/k$ output frames, then this means that we
must perform $N^(2)/k^(2)$ compatibility
checks—a factor of $k$ fewer than the
number of matches required in our current method.

Devise an implementation of #py("and") that uses
this strategy. You must implement a
function
that takes two frames as inputs, checks whether the bindings in the
frames are compatible, and, if so, produces a frame that merges the two
sets of bindings. This operation is similar to unification.
])

#exercise(label-name: <ex:not-query-filter>, [
In section @sec:math-logic we saw that
#idx("query interpreter", sub: "improvements to")
#idx("query interpreter", sub: "problems with not and javascriptpredicate")
#idx("compound query", sub: "processing")
#idx("not (query language)", sub: "evaluation of")
#py("not") and
#idx("javascriptpredicate (query language)", sub: "evaluation of")
#py("javascript_predicate")
can cause the query language to give "wrong" answers if
these filtering operations are applied to frames in which variables
are unbound. Devise a way to fix this shortcoming. One idea is to
perform the filtering in a "delayed" manner by appending to
the frame a "promise" to filter that is fulfilled only when
enough variables have been bound to make the operation possible. We could
wait to perform filtering until all other operations have been performed.
However, for efficiency's sake, we would like to perform filtering
as soon as possible so as to cut down on the number of intermediate frames
generated.
])

#exercise(label-name: <ex:query-lang-amb>, [
Redesign the query language as a
#idx("query interpreter", sub: "as nondeterministic program")
nondeterministic program to be
implemented using the evaluator of
section @sec:nondeterministic-evaluation, rather than as a stream
process. In this approach, each query will produce a single answer
(rather than the stream of all answers) and the user can type
#py("retry")
to see more answers. You should find that much of the mechanism we built
in this section is subsumed by nondeterministic search and backtracking.
You will probably also find, however, that your new query language has
subtle differences in behavior from the one implemented here. Can you
find examples that illustrate this difference?
])

#exercise(label-name: <ex:query-local-names>, [
When we implemented the
Python
evaluator in section @sec:mc-eval, we saw how to use
local environments to avoid
#idx("environment", sub: "renaming vs.")
#idx("query interpreter", sub: "Python interpreter vs.")
name conflicts between the parameters of
functions.
For example, in evaluating

#snippet(```python
def square(x):
    return x * x
def sum_of_squares(x, y):
    return square(x) + square(y)
sum_of_squares(3, 4)
```)

there is no confusion between the #py("x") in
#py("square") and the #py("x")
in
#py("sum_of_squares"),
because we evaluate the body of each
function
in an environment that is specially constructed to contain
bindings for the local
names.
In the query system, we used a
different strategy to avoid name conflicts in applying rules. Each
time we apply a rule we rename the variables with new names that are
guaranteed to be unique. The analogous strategy for the
Python
evaluator would be to do away with local environments and simply
rename the variables in the body of a
function
each time we apply the
function.

Implement for the query language a rule-application method that uses
environments rather than renaming. See if you can build on your
environment structure to create constructs in the query language for
dealing with large systems, such as the rule analog of
#idx("block structure", sub: "in query language")
#idx("environment", sub: "in query interpreter")
#idx("query interpreter", sub: "environment structure in")
#idx("rule (query language)", sub: "applying")
block-structured
functions.
Can you relate any of this to the problem of making deductions in a
context (e.g., "If I supposed that $P$ were true, then I would be able to deduce $A$ and $B$.") as a method of problem
solving? (This problem is open-ended.)
])
