// Generated from the SICP XML sources by tools/convert.py — do not edit.
#import "../../../lib/sicp.typ": *

#subsection([Applying Simple Functions], label-name: <sec:env-apply-proc>)

#idx("environment model of evaluation", sub: "function-application example")
#idx("function application", sub: "environment model of")

#idx("sumofsquares", sub: "in environment model")
When we introduced the substitution model in
section @sec:substitution-model we showed how the
application #py("f(5)")
evaluates to 136, given the following
function definitions:

#snippet(```python
def square(x):
    return x * x

def sum_of_squares(x, y):
    return square(x) + square(y)

def f(a):
    return sum_of_squares(a + 1, a * 2)
```)

We can analyze the same example using the environment model.
Figure @fig:sum-squares shows the three
function
objects created by evaluating the definitions of
#py("f"), #py("square"), and
#py("sum_of_squares")
in the
program
environment. Each
function
object consists of some code, together with a pointer to the
program
environment.

#sicp-figure(image("/images/img_javascript/ch3-Z-G-5.svg", width: 70%), caption: [Function objects in the program frame.], label-name: <fig:sum-squares>)

In
figure @fig:f5-eval
we see the environment structure created by evaluating the expression
#py("f(5)").
The call to #py("f") creates a new environment, E1,
beginning with a frame in which #py("a"), the
 parameter of
#py("f"), is bound to the argument 5. In E1, we
evaluate the body of #py("f"):

#snippet(```python
return sum_of_squares(a + 1, a * 2)
```)

To evaluate
the return statement, we first evaluate the subexpressions of the return expression.
The first subexpression,
#py("sum_of_squares"),
has a value that is a
function
object. (Notice how this value is found: We first look in the first frame
of E1, which contains no binding for
#py("sum_of_squares").
Then we proceed to the enclosing environment, i.e., the
program
environment, and find the binding shown in
figure @fig:sum-squares.)
The other two subexpressions are evaluated by applying the primitive
operations #py("+") and #py("*")
to evaluate the two combinations
#py("a + 1")
and
#py("a * 2")
to obtain 6 and 10, respectively.

Now we apply the
function
object
#py("sum_of_squares")
to the arguments 6 and 10. This results in a new environment, E2, in which
the  parameters
#py("x") and #py("y") are bound
to the arguments. Within E2 we evaluate
the statement #snippet(```python return square(x) + square(y) ```)
This leads us to evaluate
#py("square(x)"),
where #py("square") is found in the
program
frame and #py("x") is 6. Once again, we set up a
new environment, E3, in which #py("x") is bound to 6,
and within this we evaluate the body of #py("square"),
which is
#py("return x * x").
Also as part of applying
#py("sum_of_squares"),
we must evaluate the subexpression
#py("square(y)"),
where #py("y") is 10. This second call to
#py("square") creates another environment, E4, in
which #py("x"), the
 parameter of
#py("square"), is bound to 10. And within E4 we must
evaluate
#py("return x * x").

The important point to observe is that each call to
#py("square") creates a new environment containing a
binding for #py("x"). We can see here how the
different frames serve to keep separate the different local variables all
named #py("x"). Notice that each frame created by
#py("square") points to the
program
environment, since this is the environment indicated by the
#py("square")
function
object.

After the subexpressions are evaluated, the results are returned. The
values generated by the two calls to #py("square") are
added by
#py("sum_of_squares"),
and this result is returned by #py("f").
Since our focus here is on the environment structures, we will not
dwell on how these returned values are passed from call to call;
however, this is also an important aspect of the evaluation process,
and we will return to it in detail in chapter @chap:reg.
#idx("sumofsquares", sub: "in environment model")

#exercise(label-name: <ex:factorial-env-model>, [
In section @sec:recursion-and-iteration
we used the substitution model to analyze two
#idx("recursive process", sub: "iterative process vs.")
#idx("iterative process", sub: "recursive process vs.")
functions
for computing
#idx("factorial", sub: "environment structure in evaluating")
factorials, a recursive version

#snippet(```python
def factorial(n):
    return (1
            if n == 1
            else n * factorial(n - 1))
```)

and an iterative version

#snippet(```python
def factorial(n):
    return fact_iter(1, 1, n)

def fact_iter(product, counter, max_count):
    return (product
            if counter > max_count
            else fact_iter(counter * product,
                           counter + 1,
                           max_count))
```)

Show the environment structures created by evaluating
#py("factorial(6)")
using each version of the #py("factorial")
function.#footnote[The environment model will not clarify our claim in
section @sec:recursion-and-iteration that the
interpreter can execute a
function
such as
#py("fact_iter")
in a constant amount of space using tail recursion. We will discuss
#idx("environment model of evaluation", sub: "tail recursion and")
#idx("tail recursion", sub: "environment model of evaluation and")
tail recursion when we
deal with the control structure of the interpreter in
section @sec:eceval.]
])

#idx("environment model of evaluation", sub: "function-application example")
#idx("function application", sub: "environment model of")

#sicp-figure(image("/images/img_javascript/ch3-Z-G-6.svg", width: 70%), caption: [Environments created by evaluating #py("f(5)") using the functions in figure @fig:sum-squares.], label-name: <fig:f5-eval>)
