// Generated from the SICP XML sources by tools/convert.py — do not edit.
#import "../../../lib/sicp.typ": *

#subsection([Orders of Growth], label-name: <sec:orders-of-growth>)

#idx("order of growth")

The previous examples illustrate that processes can differ
considerably in the rates at which they consume computational
resources. One convenient way to describe this difference is to use
the notion of
#idx("process", sub: "order of growth of")
#emph[order of growth] to obtain a gross measure of the
#idx("process", sub: "resources required by")
resources required by a process as the inputs become larger.

Let $n$ be a parameter that measures the size of
the problem, and let $R(n)$ be the amount
of resources the process requires for a problem of size
$n$. In our previous examples we took
$n$ to be the number for which a given
function is to be computed, but there are other possibilities.
For instance, if our goal is to compute an approximation to the
square root of a number, we might take
$n$ to be the number of digits accuracy required.
For matrix multiplication we might take $n$ to
be the number of rows in the matrices. In general there are a number of
properties of the problem with respect to which it will be desirable to
analyze a given process. Similarly, $R(n)$
might measure the number of internal storage registers used, the
number of elementary machine operations performed, and so on. In
computers that do only a fixed number of operations at a time, the
time required will be proportional to the number of elementary machine
operations performed.

We say that $R(n)$ has order of growth
#idx("θ(f(n)) (theta of f(n))", sort: "0e")
#idx("θ(f(n)) (theta of f(n))", sort: "theta")
#idx("order notation")
$Theta (f(n))$, written
$R(n)= Theta (f(n))$ (pronounced
"theta of $f(n)$"), if there are
positive constants $k_(1)$ and
$k_(2)$ independent of
$n$ such that

$ mat(delim: #none, k_(1) thin f(n), lt.eq, R(n), lt.eq, k_(2) thin f(n)) $

for any sufficiently large value of $n$.
(In other words, for large $n$,
the value $R(n)$ is sandwiched between
$k_(1)f(n)$ and
$k_(2)f(n)$.)

#idx("order of growth", sub: "linear recursive process")
#idx("linear recursive process", sub: "order of growth")
#idx("recursive process", sub: "linear")
For instance, with the linear recursive process for computing factorial
described in section @sec:recursion-and-iteration the
number of steps grows proportionally to the input
$n$. Thus, the steps required for this process
grows as $Theta (n)$. We also saw that the space
required grows as $Theta (n)$. For the
#idx("order of growth", sub: "linear iterative process")
#idx("linear iterative process", sub: "order of growth")
#idx("iterative process", sub: "linear")
iterative factorial, the number of steps is still
$Theta (n)$ but the space is
$Theta (1)$—that is,
constant.#footnote[These statements mask a great deal of oversimplification.
For instance, if we count process steps as "machine operations"
we are making the assumption that the number of machine operations needed to
perform, say, a multiplication is independent of the size of the numbers to
be multiplied, which is false if the numbers are sufficiently large.
Similar remarks hold for the estimates of space. Like the design and
description of a process, the analysis of a process can be carried out at
various levels of abstraction.]
The
#idx("order of growth", sub: "tree-recursive process")
#idx("tree-recursive process", sub: "order of growth")
#idx("recursive process", sub: "tree")
tree-recursive Fibonacci computation requires
$Theta ( phi ^(n))$ steps and space
$Theta (n)$, where
$phi$ is the golden ratio described in
section @sec:tree-recursion.

Orders of growth provide only a crude description of the behavior of a
process. For example, a process requiring $n^(2)$
steps and a process requiring $1000n^(2)$ steps and
a process requiring $3n^(2)+10n+17$ steps all have
$Theta (n^(2))$ order of growth. On the other hand,
order of growth provides a useful indication of how we may expect the
behavior of the process to change as we change the size of the problem.
For a
#idx("linear growth")
$Theta (n)$ (linear) process, doubling the size
will roughly double the amount of resources used. For an
#idx("exponential growth")
exponential process, each increment in problem size will multiply the
resource utilization by a constant factor. In the remainder of
section @sec:procedures-and-processes
we will examine two algorithms whose order of growth is
#idx("logarithmic growth")
logarithmic, so that doubling the problem size increases the resource
requirement by a constant amount.
#idx("order of growth")

#exercise(label-name: <ex:1_14>, [
Draw the tree illustrating the process generated by the
#py("count_change") function
of section @sec:tree-recursion in making change for
11 cents. What are the orders of growth of the space and number of steps
used by this process as the amount to be changed increases?
])

#exercise(label-name: <ex:1_15>, [
#idx("sine", sub: "approximation for small angle")
The sine of an angle (specified in radians) can be computed by making use
of the approximation $sin x approx x$
if $x$ is sufficiently small, and the
trigonometric identity

$ mat(delim: #none, sin x, =, 3 sin (frac(x, 3))-4 sin ^(3)(frac(x, 3))) $

to reduce the size of the argument of $sin$.
(For purposes of this exercise an angle is considered "sufficiently small" if its magnitude is not greater than 0.1 radians.) These
ideas are incorporated in the following
functions:
#idx("cube", decl: true)
#snippet(```python
def cube(x):
    return x * x * x

def p(x):
    return 3 * x - 4 * cube(x)

def sine(angle):
    return angle if not (abs(angle) > 0.1) else p(sine(angle / 3))
```)

+ How many times is the function #py("p") applied when #py("sine(12.15)") is evaluated?
+ What is the order of growth in space and number of steps (as a function of $a$) used by the process generated by the #py("sine") function when #py("sine(a)") is evaluated?
])
